### ISSUE TITLE
jmol seems broken with 6.5.beta5

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#332]
Here on both Gentoo and prefix with 6.5.beta5 the following returns an empty jmol:
``
sage: sphere()
``
6.4 on another prefix does work.

**Comment by kiwifb** [comment]
Yes I spotted that the other day while testing the MPL 1.4 ticket but I haven't found the time to dig out what is happening.

**Comment by strogdon** [comment]
That ticket is why I found it also.

**Comment by kiwifb** [comment]
From the jmol java console
```
FileManager opening 2 /home/fbissey/.sage/temp/QCD-nzi3/15291/tmp_VEAt1Y.spt
FileManager opening 3 /home/fbissey/.sage/temp/QCD-nzi3/15291/tmp_kHYL32.spt.zip|SCRIPT
FileManager opening 2 /home/fbissey/.sage/temp/QCD-nzi3/15291/tmp_kHYL32.spt.zip
vwr handling error condition: java.lang.ClassFormatError: Extra bytes at the end of class file javajs/api/Interface  
java.lang.ClassFormatError: Extra bytes at the end of class file javajs/api/Interface
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at javajs.util.Rdr.getJzt(Unknown Source)
	at javajs.util.Rdr.getZipFileDirectory(Unknown Source)
	at org.jmol.viewer.FileManager.getUnzippedReaderOrStreamFromName(Unknown Source)
	at org.jmol.viewer.FileManager.getBufferedReaderOrErrorMessageFromName(Unknown Source)
	at org.jmol.viewer.FileManager.getFileDataOrErrorAsString(Unknown Source)
	at org.jmol.viewer.Viewer.getFileAsStringBin(Unknown Source)
	at org.jmol.script.ScriptEval.compileScriptFileInternal(Unknown Source)
	at org.jmol.script.ScriptEval.cmdScript(Unknown Source)
	at org.jmol.script.ScriptEval.processCommand(Unknown Source)
	at org.jmol.script.ScriptEval.commandLoop(Unknown Source)
	at org.jmol.script.ScriptEval.dispatchCommands(Unknown Source)
	at org.jmol.script.ScriptEval.cmdScript(Unknown Source)
	at org.jmol.script.ScriptEval.processCommand(Unknown Source)
	at org.jmol.script.ScriptEval.commandLoop(Unknown Source)
	at org.jmol.script.ScriptEval.dispatchCommands(Unknown Source)
	at org.jmol.script.ScriptEval.executeCommands(Unknown Source)
	at org.jmol.script.ScriptEval.evaluateCompiledScript(Unknown Source)
	at org.jmol.script.ScriptManager.evalStringWaitStatusQueued(Unknown Source)
	at org.jmol.viewer.Viewer.evalStringWaitStatusQueued(Unknown Source)
	at org.jmol.script.ScriptQueueThread.runNextScript(Unknown Source)
	at org.jmol.script.ScriptQueueThread.run1(Unknown Source)
	at org.jmol.thread.JmolThread.run(Unknown Source)
```
Could you compare with the output in 6.4? I got these from the "java jmol console" under the help menu.

**Comment by kiwifb** [comment]
Also are both 6.4 and 6.5.beta5 on sage-jmol-bin?

**Comment by kiwifb** [comment]
Looks like there is at least one mistake in sage/interfaces/jmoldata.py to use the new sage-jmol-bin but it may be insufficient to fix the problem.

**Comment by kiwifb** [comment]
pushed fix for jmoldata.py.

**Comment by strogdon** [comment]
Both 6.4 and 6.5.beta5 are using sage-jmol-bin. I will check the java console tomorrow. I'm away from that computer and no ssh is possible.

**Comment by kiwifb** [comment]
OK if both had sage-jmol-bin then the fix I just pushed has to be irrelevant. But the console output would be nice.

**Comment by strogdon** [comment]
Jmol Java Console output - sage-6.4:
```
FileManager opening 2 /local/gentoo-redlizard/.sage/temp/miranda/10483/tmp_zA_LcJ.spt
FileManager opening 3 /local/gentoo-redlizard/.sage/temp/miranda/10483/tmp_P0JPif.spt.zip|SCRIPT
FileManager opening 2 /local/gentoo-redlizard/.sage/temp/miranda/10483/tmp_P0JPif.spt.zip
StatusListener notifyFileLoaded: zapped
The Resolver thinks Xyz
reading 10 atoms
ModelSet: haveSymmetry:false haveUnitcells:false haveFractionalCoord:false
1 model in this collection. Use getProperty "modelInfo" or getProperty "auxiliaryInfo" to inspect them.
Default Van der Waals type for model set to Babel
10 atoms created
ModelSet: autobonding; use  autobond=false  to not generate bonds automatically
StatusListener notifyFileLoaded: string
no data
isosurface sphere_1  center {0.0 0.0 0.0} sphere 3.0;
sphere_1 created with cutoff=1.4E-45; isosurface count: 1

1 id:sphere_1; model:1.1; vertices:1440; polygons:2876; visible:true; dataRange:[0.0, 0.0, 0.0, 0.0]; title:isosurface sphere_1  center {0.0 0.0 0.0} sphere 3.0;

pmesh o* fullylit;
```

**Comment by kiwifb** [comment]
Would you be able to send me /local/gentoo-redlizard/.sage/temp/miranda/10483/tmp_P0JPif.spt.zip please?

**Comment by kiwifb** [comment]
Hum.... Do you have the same version of java 1.7 on both machine? If not which versions?

**Comment by kiwifb** [comment]
Also what is the on screen output when you run jmol directly as in 
```
jmol /local/gentoo-redlizard/.sage/temp/miranda/10483/tmp_P0JPif.spt.zip
```
on the sage 6.4 machine?

**Comment by strogdon** [comment]
No I don't. I was just going there.

prefix with 6.4 - oracle-jdk-bin-1.7.0.67
gentoo with 6.5.beta5 - oracle-jdk-bin-1.7.0.55
prefix with 6.5.beta5 - oracle-jdk-bin-1.7.0.72

**Comment by strogdon** [comment]
screen output of:
``
jmol /local/gentoo-redlizard/.sage/temp/miranda/3809/tmp_UGiHpr.spt.zip
``
```
splash_image=jar:file:/local/gentoo-redlizard/usr/share/sage-jmol-bin/lib/Jmol.jar!/org/openscience/jmol/app/images/Jmol_splash.jpg
history file is /home/umd/.jmol/history
(C) 2012 Jmol Development
Jmol Version: 14.2.4_2014.08.03  2014-08-03 08:56
java.vendor: Java: Oracle Corporation
java.version: Java 1.7.0_67
os.name: Linux
Access: ALL
memory: 29.9/124.3
processors available: 4
useCommandThread: false
User macros dir: /home/umd/.jmol/macros
       exists: false
  isDirectory: false
Executing script: load "/local/gentoo-redlizard/.sage/temp/miranda/3809/tmp_UGiHpr.spt.zip";
```

**Comment by kiwifb** [comment]
And it displays a sphere propery?

**Comment by strogdon** [comment]
No it doesn't. I get in the jmol window
```
unrecognized file format for file
/local/gentoo-redlizard/.sage/temp/miranda/3809/tmp_UGiHpr.spt.zip
SCRIPT

data "model list"

10

empty
````

**Comment by strogdon** [comment]
If I process through jmol the file with just the ``.spt`` extension then I get the sphere.

**Comment by kiwifb** [comment]
And a similar on screen output?

**Comment by strogdon** [comment]
Yes, similar screen output.

**Comment by kiwifb** [comment]
OK so now I can get the sphere with vanilla sage-6.5.beta5 jmol but not the system wide jmol. The mystery is how you get it on the sage 6.4 machine.
```
equery b `which jmol`
```
on that machine?

**Comment by strogdon** [comment]
```
equery b `which jmol`
 * Searching for /local/gentoo-redlizard/usr/bin/jmol ...

sci-chemistry/sage-jmol-bin-14.2.4 (/local/gentoo-redlizard/usr/bin/jmol)
```

**Comment by kiwifb** [comment]
OK so we really have the same jmol. If I manually unpack the zip file the result is a file called SCRIPT. If I do "jmol -s SCRIPT" I get the right thing with the system jmol so there must be something not right in the unpacking sequence.

**Comment by kiwifb** [comment]
It appear that the Gentoo generated jmol launcher script may be broken
```
java -Xmx512m -jar /usr/share/sage-jmol-bin/lib/Jmol.jar -l .sage/temp/QCD-nzi3/15572/tmp_a6hlw7.spt
```
worked. I must say launcher.bash from java-config doesn't look too healthy to me. So what version of java-config are on the various machines?

**Comment by strogdon** [comment]
I have ``java-config-2.1.11-r3`` on both prefix machines and ``java-config-2.2.0`` on gentoo.

**Comment by kiwifb** [comment]
I think I got it could you post the content of ${PREFIX}/usr/share/sage-jmol-bin/package.env on the 6.4 machine? If it doesn't show what I am expecting I will a working solution for completely unknown reason.

**Comment by strogdon** [comment]
cat ~/usr/share/sage-jmol-bin/package.env [~ is ${EPREFIX}]
```
DESCRIPTION="Jmol is a java molecular viever for 3-D chemical structures."
GENERATION="2"
SLOT="0"
CATEGORY="sci-chemistry"
PVR="14.2.4"
CLASSPATH="/local/gentoo-redlizard//usr/share/sage-jmol-bin/lib/JSpecView.jar:/local/gentoo-redlizard//usr/share/sage-jmol-bin/lib/Jmol.jar:/local/gentoo-redlizard//usr/share/sage-jmol-bin/lib/JmolData.jar:/local/gentoo-redlizard//usr/share/sage-jmol-bin/lib/JmolLib.jar"
VM=">=virtual/jre-1.7"
TARGET="1.7"
SOURCE="1.7"
MERGE_VM=""
```
This looks like what I have on the other machines.

**Comment by kiwifb** [comment]
So It is a complete mystery but putting Jmol.jar first in CLASSPATH seems to solve the problem here. There may be an extra ingredient in what make things fall over. Updating the sage-jmol-bin ebuild so we have an order that makes things work. Cross fingers.

**Comment by strogdon** [comment]
Strange! Who would have thought? But with the fix jmol now works everywhere here.

**Comment by kiwifb** [comment]
OK closing that one!
