### ISSUE TITLE
sage-6.5 won't emerge: 'sage/tests/parallel.pyx' doesn't match any files

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#336]
The sage 6.5 ebuild fails to emerge for me:

```
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
Building interpreters for fast_callable
Updating Cython code....
Enabling Cython debugging support
Traceback (most recent call last):
  File "setup.py", line 565, in <module>
    run_cythonize()
  File "setup.py", line 557, in run_cythonize
    'profile': profile,
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
    aliases=aliases)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
    for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
    raise ValueError(error_msg)
ValueError: 'sage/tests/parallel.pyx' doesn't match any files
 * ERROR: sci-mathematics/sage-6.5::sage-on-gentoo failed (compile phase):
 *   (no error message)
```

**Comment by kiwifb** [comment]
You have cython 0.22 I should make the dependency on cython stricter. Please downgrade cython and retry.

**Comment by kiwifb** [comment]
OK pushed stricter dependency on cython. Re-open if it is still a problem.

**Comment by devurandom** [comment]
Affects 6.4-r1, too. Please reopen.

```
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-mathematics/sage-6.4-r1/work/sage-6.4/src ...
 ^[[32;01m*^[[0m python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
Building interpreters for fast_callable
Updating Cython code....
Enabling Cython debugging support
Traceback (most recent call last):
  File "setup.py", line 565, in <module>
    run_cythonize()
  File "setup.py", line 557, in run_cythonize
    'profile': profile,
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 754, in cythonize
    aliases=aliases)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
    for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 103, in nonempty
    raise ValueError(error_msg)
ValueError: 'sage/tests/parallel.pyx' doesn't match any files
 ^[[31;01m*^[[0m ERROR: sci-mathematics/sage-6.4-r1::sage-on-gentoo failed (compile phase):
````

**Comment by kiwifb** [comment]
Please sync. Your sage ebuild should depend on 
```
~dev-python/cython-0.21.1[${PYTHON_USEDEP}]
```
package.keywords/sage-6.4 has also been updated to only show cython-0.21.1. Yet you are using cython-0.22.

**Comment by devurandom** [comment]
What about dev-python/cython-0.21.2? That also does not work with sage-6.4?

**Comment by kiwifb** [comment]
No idea. But the problem with parallel.pyx is specific to 0.22+. Just removing it is not helpful as there was more stuff done in the ticket to upgrade to 0.22. 

My bet is that 0.21.2 would work but I haven't tried.

**Comment by devurandom** [comment]
I just tried. It works.

**Comment by kiwifb** [comment]
OK I will add stuff for 6.4 and 6.5. Why are you still on 6.4 by the way?

**Comment by devurandom** [comment]
Because that is the latest version in my checkout. Apparently layman does not properly update it for me…

**Comment by kiwifb** [comment]
If someone is really wanting cython 0.22 backporting to 6.4 and 6.5 should be relatively trivial. See
http://trac.sagemath.org/ticket/17657
