### ISSUE TITLE
sci-mathematics/sage-doc-6.6 - OSError: [repl     ] WARNING: the config value 'nitpick_ignore' has type `tuple', defaults to `list.'

### ISSUE THREAD

**Issue by devurandom** [cschwan/sage-on-gentoo#346]
sci-mathematics/sage-doc-6.6 fails to build with following error:
```
 * Package:    sci-mathematics/sage-doc-6.6
 * Repository: sage-on-gentoo
 * Maintainer: sci@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc html kernel_linux linguas_de linguas_en python_targets_python2_7 userland_GNU
 * FEATURES:   compressdebug preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking sage-6.6.tar.gz to /var/tmp/portage/sci-mathematics/sage-doc-6.6/work
>>> Unpacking Singular-3-1-6-share.tar.gz to /var/tmp/portage/sci-mathematics/sage-doc-6.6/work
>>> Source unpacked in /var/tmp/portage/sci-mathematics/sage-doc-6.6/work
>>> Preparing source in /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src ...
 * Applying sage-doc-6.0-misc.patch ...                                                                                                                                                                                                 [ ok ]
 * Applying sage-doc-6.6-linguas.patch ...                                                                                                                                                                                              [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src ...
 * python2_7: running distutils-r1_run_phase python_compile
Setting permissions of DOT_SAGE directory so only you can read and write it.

Building reference manual, first pass.

[polynomia] WARNING: the config value 'nitpick_ignore' has type `tuple', defaults to `list.'
[repl     ] WARNING: the config value 'nitpick_ignore' has type `tuple', defaults to `list.'
[repl     ] WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
[polynomia] WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/fancy_repr.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/util.rst:: WARNING: env.currclass is being referenced by an extension; this API will be removed in the future
[repl     ] /var/tmp/portage/sci-mathematics/sage-doc-6.6/work/sage-6.6/src/doc/en/reference/repl/sage/repl/display/util.rst:: WARNING: env.currmodule is being referenced by an extension; this API will be removed in the future
Error building the documentation.
Traceback (most recent call last):
  File "doc/common/builder.py", line 1626, in <module>
    getattr(get_builder(name), type)()
  File "doc/common/builder.py", line 292, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "doc/common/builder.py", line 503, in _wrapper
    x.get(99999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
OSError: [repl     ] WARNING: the config value 'nitpick_ignore' has type `tuple', defaults to `list.'
```

The same happened with sci-mathematics/sage-doc-6.5.

```
# emerge --info
Portage 2.2.18 (python 3.4.3-final-0, default/linux/amd64/13.0/desktop/kde/systemd, gcc-4.9.2, glibc-2.20-r2, 4.0.0-gentoo x86_64)
=================================================================
System uname: Linux-4.0.0-gentoo-x86_64-AMD_Athlon-tm-_64_X2_Dual_Core_Processor_5000+-with-gentoo-2.2
KiB Mem:     6107016 total,    221956 free
KiB Swap:    7813116 total,   6640836 free
Timestamp of repository gentoo: Wed, 15 Apr 2015 20:15:01 +0000
Timestamp of repository kde: Wed, 15 Apr 2015 21:00:14 +0000
sh bash 4.3_p33-r2
ld GNU ld (Gentoo 2.25 p1.0) 2.25
ccache version 3.2.1 [disabled]
app-shells/bash:          4.3_p33-r2::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.9-r2::gentoo, 3.3.5-r1::gentoo, 3.4.3::gentoo
dev-util/ccache:          3.2.1-r1::gentoo
dev-util/cmake:           3.2.1::gentoo
dev-util/pkgconfig:       0.28-r2::gentoo
sys-apps/baselayout:      2.2::gentoo
sys-apps/openrc:          0.13.11::gentoo
sys-apps/sandbox:         2.6-r1::gentoo
sys-devel/autoconf:       2.13::gentoo, 2.69-r1::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.12.6::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25::gentoo
sys-devel/gcc:            4.9.2::gentoo
sys-devel/gcc-config:     1.8::gentoo
sys-devel/libtool:        2.4.6-r1::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 4.0::gentoo (virtual/os-headers)
sys-libs/glibc:           2.20-r2::gentoo
Repositories:

gentoo
    location: /var/cache/portage/gentoo
    sync-type: rsync
    sync-uri: […]
    priority: -1000

kde
    location: /var/cache/portage/overlays/kde
    sync-type: rsync
    sync-uri: […]
    masters: gentoo

sage-on-gentoo
    location: /var/lib/layman/sage-on-gentoo
    sync-type: laymansync
    sync-uri: git://github.com/cschwan/sage-on-gentoo.git
    masters: gentoo
    priority: 50

local
    location: /var/cache/portage/local
    masters: gentoo
    priority: 100

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-pipe -O2 -march=athlon64-sse3"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt /usr/share/themes/oxygen-gtk/gtk-2.0 /usr/share/themes/oxygen-gtk/gtk-3.0 /var/lib/hsqldb"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-pipe -O2 -march=athlon64-sse3"
DISTDIR="/var/cache/portage/distfiles"
EMERGE_DEFAULT_OPTS="--keep-going --nospinner"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs buildsyspkg compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch parallel-install preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="http://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/ http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ http://distfiles.gentoo.org"
LANG="en_GB.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"
MAKEOPTS="-j2"
PKGDIR="/var/cache/portage/packages"
PORTAGE_COMPRESS="xz"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac aacplus aacs acl acpi alsa amd64 avahi bash-completion bdplus berkdb bluetooth bluray branding bzip2 cairo caps cdda cddb cdio cdr celt cjk cli cracklib crypt cups cxx dbus declarative dirac dri dts dvb dvd dvdr egl emboss encode exif fam fax ffmpeg firefox flac fortran gdbm gif glamor gles gles2 gmp gpm gstreamer gtk ibus iconv ipv6 jpeg jpeg2k kde kipi ladspa latex lcms ldap libnotify libsecret lua_target_lua5-2 lv2 lz4 lzma lzo mad mmx mmxext mng modemmanager modplug modules mp3 mp4 mpeg mplayer mtp multilib mysql ncurses networkmanager nls nptl ogg openal opencl openexr opengl openmp opus pam pango pch pcre pdf phonon plasma png policykit ppds pulseaudio qt3support qt4 qt5 readline rtmp samba scanner schroedinger sctp sdl semantic-desktop session speex spell sse sse2 ssl startup-notification subversion svg systemd tcpd theora threads tiff truetype udev udisks unicode upnp upower usb v4l vaapi vdpau vorbis vpx wavpack wayland webp x264 x265 xattr xcb xcomposite xinerama xml xscreensaver xv xvid xz zeroconf zlib" ABI_X86="64" ALSA_CARDS="hda-intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="stage words flow sheets" CAMERAS="ptp2" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="3dnow 3dnowext mmx mmxext sse sse2 sse3" DRACUT_MODULES="btrfs systemd" ELIBC="glibc" ENLIGHTENMENT_MODULES="*" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="pc" INPUT_DEVICES="evdev joystick" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LINGUAS="de en en_GB ar fa" LIRC_DEVICES="devinput" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_3 python3_4" RUBY_TARGETS="ruby22" USERLAND="GNU" VIDEO_CARDS="radeon r600" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
USE_PYTHON="2.7 3.3 3.4"
Unset:  CPPFLAGS, CTARGET, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by kiwifb** [comment]
What version of `sphinx` do you use? I haven't tested 1.3 yet. I also recommend most people to use sage-doc-bin rather than sage-doc.

**Comment by devurandom** [comment]
dev-python/sphinx-1.3.1

sci-mathematics/sage-doc was automatically installed. I did not even know a binary package existed.

**Comment by kiwifb** [comment]
I have to check why it default to that for you. Stable users using our `package.keywords/sage` file only get `sage-doc-bin` but you are on ~amd64.

**Comment by kiwifb** [comment]
OK I forgot to do something when I released sage 6.6. So now you should be able to pull `sage-doc-bin`. If sage is already merged you may need to re-emerge it first. Hopefully sage-doc-bin will be pulled by default for you. If it isn't I'll have to think of something.

**Comment by kiwifb** [comment]
Also did something for the sphinx dependency so I believe we have sorted everything now.

**Comment by devurandom** [comment]
sage-doc-bin-6.6 is broken:
```
>>> Preparing source in /var/tmp/portage/sci-mathematics/sage-doc-bin-6.6/work/sage-6.6/src/doc ...
 * Applying sage-doc-bin-6.0-misc.patch ...                                                                                                                                                                                             [ ok ]
 * QA: File or directory "/var/lib/layman/sage-on-gentoo/sci-mathematics/sage-doc-bin/files/sage-doc-6.6-linguas.patch" does not exist.
 * QA: Check your PATCHES array or add missing file/directory.
```

**Comment by kiwifb** [comment]
Thanks for spotting that one, it has been present unnoticed for a few weeks in the ancestor of that ebuild.

**Comment by kiwifb** [comment]
Is it all in order now?

**Comment by devurandom** [comment]
```
>>> Install sage-doc-bin-6.6 into /var/tmp/portage/sci-mathematics/sage-doc-bin-6.6/image/ category sci-mathematics
/usr/bin/install: cannot stat ‘output/html/*’: No such file or directory
!!! doins: output/html/* does not exist
```

**Comment by kiwifb** [comment]
OK definitely not my finest job.

**Comment by kiwifb** [comment]
OK My generated tarball needs fixing. I wish upstream would just put something on their mirror in a matter of hours rather than weeks.

**Comment by kiwifb** [comment]
And this install here, I hope it does for you too.

**Comment by devurandom** [comment]
Is it possible to add a check for enough inodes to sage-doc (non-bin)? I run out of disk "space" at 4.6 of 8.0 GiB on /var/tmp/portage.

**Comment by kiwifb** [comment]
Yes definitely. That's one of the reason sage-doc-bin is preferable to sage-doc. Upstream has patched mathjax in a way it doesn't produce quite the same amount of files. And of course things are worse if you don't set `LINGUAS`.  I'll to check if we have checks for inodes. I know we have for space, if you have an ebuild to point too that would be helpful.

**Comment by kiwifb** [comment]
It doesn't look like we have a check for inode in the appropriate eclass https://devmanual.gentoo.org/eclass-reference/check-reqs.eclass/index.html but installation space for the current sage-doc is several GB so should be checked. I am working on reducing that. Building space is at least equal to building space.

**Comment by devurandom** [comment]
sage-doc-bin-6.6 builds fine now. Thanks!
