### ISSUE TITLE
maxima interface failure: /usr/share/sage/src/sage/interfaces/maxima.py

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#356]
The failure on Gentoo with `sage-6.8.beta2` is:
```
sage -t --long /usr/share/sage/src/sage/interfaces/maxima.py
too many failed tests, not using stored timings
Running doctests with ID 2015-06-02-12-39-58-2a392015.
Doctesting 1 file.
sage -t --long /usr/share/sage/src/sage/interfaces/maxima.py
**********************************************************************
File "/usr/share/sage/src/sage/interfaces/maxima.py", line 594, in sage.interfaces.maxima.Maxima._start
Failed example:
    b = a^600              # long time -- about 10-15 seconds
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 496, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 858, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.maxima.Maxima._start[5]>", line 1, in <module>
        b = a**Integer(600)              # long time -- about 10-15 seconds
      File "/usr/lib64/python2.7/site-packages/sage/interfaces/interface.py", line 1118, in __pow__
        return self._operation("^", n)
      File "/usr/lib64/python2.7/site-packages/sage/interfaces/maxima_abstract.py", line 1915, in _operation
        raise TypeError(msg)
    TypeError: End Of File (EOF) in read_nonblocking(). Exception style platform.
    <sage_pexpect.spawn instance at 0x7faa69cd7170>
    version: 2.0 ($Revision: 1.151 $)
    command: /usr/bin/maxima
    args: ['/usr/bin/maxima', '-l', 'ecl', '--userdir=/home/volj/27/strogdon/.sage/maxima', '-p', '/usr/bin/sage-maxima.lisp']
    patterns:
        <sage-display>
    buffer (last 100 chars): 
    before (last 100 chars): Duplicate large block deallocation

    after: <class 'sage_pexpect.EOF'>
    match: None
    match_index: None
    exitstatus: None
    flag_eof: 1
    pid: 25785
    child_fd: 12
    timeout: None
    delimiter: <class 'sage_pexpect.EOF'>
    logfile: None
    maxread: 10000
    searchwindowsize: None
    delaybeforesend: 0
**********************************************************************
File "/usr/share/sage/src/sage/interfaces/maxima.py", line 626, in sage.interfaces.maxima.Maxima._sendline
Failed example:
    maxima.get('t')
Expected:
    '9'
Got:
    Maxima crashed -- automatically restarting.
    't'
**********************************************************************
2 items had failures:
   1 of   3 in sage.interfaces.maxima.Maxima._sendline
   1 of   7 in sage.interfaces.maxima.Maxima._start
    [179 tests, 2 failures, 7.39 s]
----------------------------------------------------------------------
sage -t --long /usr/share/sage/src/sage/interfaces/maxima.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 7.5 seconds
    cpu time: 2.3 seconds
    cumulative wall time: 7.4 seconds
```
I'm guessing the second failure is related to the first. This test has been around for some time http://trac.sagemath.org/ticket/6772 and what is odd is that the test has not always failed. It started to fail somewhere between `6.5.beta2` and `6.6.rc0`. This does not fail will vanilla Sage on the same Gentoo box. From the Gentoo sage prompt
```
sage: maxima._sendline(":lisp (ext:set-limit 'ext:heap-size 0)")
sage: a = maxima(10)^(10^5)
sage: b = a^600
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-d9483afd389d> in <module>()
----> 1 b = a**Integer(600)

/usr/lib64/python2.7/site-packages/sage/interfaces/interface.pyc in __pow__(self, n)
   1116         if parent(n) is not P:
   1117             n = P(n)
-> 1118         return self._operation("^", n)
   1119 
   1120 def reduce_load(parent, x):

/usr/lib64/python2.7/site-packages/sage/interfaces/maxima_abstract.pyc in _operation(self, operation, right)
   1913             return P.new('%s %s %s'%(self._name, operation, right._name))
   1914         except Exception as msg:
-> 1915             raise TypeError(msg)
   1916 
   1917 

TypeError: End Of File (EOF) in read_nonblocking(). Exception style platform.
<sage_pexpect.spawn instance at 0x7f6eacdedbd8>
version: 2.0 ($Revision: 1.151 $)
command: /usr/bin/maxima
args: ['/usr/bin/maxima', '-l', 'ecl', '--userdir=/home/volj/27/strogdon/.sage/maxima', '-p', '/usr/bin/sage-maxima.lisp']
patterns:
    <sage-display>
buffer (last 100 chars): 
before (last 100 chars): Duplicate large block deallocation

after: <class 'sage_pexpect.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: 1
pid: 26719
child_fd: 5
timeout: None
delimiter: <class 'sage_pexpect.EOF'>
logfile: None
maxread: 10000
searchwindowsize: None
delaybeforesend: 0
```
And perhaps even more odd is that I have a prefix on which there is no failure (`sage-6.8.beta2`) and one on which there is (`sage-6.7`).

**Comment by strogdon** [comment]
The upper limit on the observed failure should be `6.7.rc0` and not `6.6.r0`. I have no saved test logs for `6.6.*`.

**Comment by strogdon** [comment]
So, in part, this may be known, http://sourceforge.net/p/ecls/bugs/305/. But gmp or ecls?

**Comment by kiwifb** [comment]
I have started spotting it in 6.8.beta2 here. Not before, that being said if it related to gmp 6.0.0a that would roughly match when I started to get bad stuff. Checking.

**Comment by kiwifb** [comment]
Confirmed that is our bug, I'll had it to the know failures. It goes along `sage/libs/libecm.pyx` which also has a failing test because of `gmp-6.0.0a` I got in touch with `gmp-ecm` upstream for that one by the way and their answer is interesting: "I think the new `gmp` behaviour is better".

**Comment by strogdon** [comment]
Yes, it's `gmp-6`. I downgraded to `gmp-5.1.3-r1`, which was a chore because `ppl` depends on `gmp-6` and this seemed to fix `sage/interfaces/maxima.py` along with `sage/libs/libecm.pyx` failures. ppl does appear to build successfully against `gmp-5`. I'm not sure why `gmp-6` is required?

**Comment by kiwifb** [comment]
Which `ppl` do you have? `ppl-1.1` from the main tree dies an horrible death here against `gmp-5.1.3-r1`
```
libtool: compile:  x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I.. -I.. -I../src -frounding-math -O1 -march=native -pipe -ggdb -W -Wall -c Grid_Generator.cc  -fPIC -DPIC -o .libs/Grid_Generator.o
In file included from Expression_Adapter_defs.hh:30:0,
                 from Linear_Expression_defs.hh:48,
                 from Constraint_defs.hh:36,
                 from Constraint.cc:25:
Dense_Row_defs.hh:436:11: error: 'ptrdiff_t' does not name a type
   typedef ptrdiff_t difference_type;
 ```
quite a few times before quitting. I used to have an ebuild in a private overlay - that I unfortunately cleaned up that worked against 5.1.3-r1.

**Comment by strogdon** [comment]
Yes, `ppl-1.1` from the main tree is what I used. But it built here?

**Comment by kiwifb** [comment]
`gcc` version?

**Comment by strogdon** [comment]
gcc version 4.8.4 (Gentoo 4.8.4 p1.4, pie-0.6.1)

**Comment by kiwifb** [comment]
I have `4.9.2` so it is probably relate to `gcc`.

**Comment by strogdon** [comment]
Interesting that vanilla Sage has the option of using their gcc, which is 4.9.2 and they install ppl-1.1.

**Comment by kiwifb** [comment]
Point taken, I should check the patches but that will probably mean carrying our own ppl again.

**Comment by strogdon** [comment]
It looks like there is a patch to deal with `ptrdiff_t difference_type` issues.

**Comment by kiwifb** [comment]
OK, unkeyworded gmp 6.0.0a and provided an alternative ppl in the overlay. I think we should keep this isuue open to monitor the `ecls` bug. I am not worried about libecm as it is only affecting a corner case that happens to be doctested. But ecls is more serious.

**Comment by kiwifb** [comment]
`gmp-6.0.0a` is now stable. Joy.

**Comment by kiwifb** [comment]
May want to move to `ecls-16.0.0` but I have found the commit I think:
https://gitlab.com/embeddable-common-lisp/ecl/commit/bd48b85970603af16318ec56d6da50a71c9d129e
so we could technically patch `15.3.7`.

**Comment by kiwifb** [comment]
Patch unfortunately doesn't take. Will try to use `ecls-16.0.0` instead.

**Comment by kiwifb** [comment]
`sage` works (tm) with `ecls 16.0.0`. Will adjust some keyword files and then close.
