### ISSUE TITLE
[sci-mathematics/sage-6.10] Fails to build sage/ext/pselect.pyc library

### ISSUE THREAD

**Issue by fusion809** [cschwan/sage-on-gentoo#387]
Hi,

I just ran `emerge -b =sage-6.10` on my Sabayon Linux machine (after syncing this overlay) and it returned this error message at the compile stage:

```bash
Compiling sage/symbolic/pynac.pyx because it changed.
Compiling sage/symbolic/ring.pyx because it changed.
Compiling sage/symbolic/substitution_map.pyx because it changed.
Compiling sage/tests/stl_vector.pyx because it changed.
Compiling sage/tests/cython.pyx because it changed.
Compiling sage/ext/interpreters/wrapper_rdf.pyx because it changed.
Compiling sage/ext/interpreters/wrapper_cdf.pyx because it changed.
Compiling sage/ext/interpreters/wrapper_rr.pyx because it changed.
Compiling sage/ext/interpreters/wrapper_py.pyx because it changed.
Compiling sage/ext/interpreters/wrapper_el.pyx because it changed.

Error compiling Cython file:
------------------------------------------------------------
...
#                  http://www.gnu.org/licenses/
#*****************************************************************************

cimport libc.errno
from posix.signal cimport *
from posix.select cimport *
^
------------------------------------------------------------

sage/ext/pselect.pyx:65:0: 'posix/select.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
            Traceback (most recent call last):
            ...
            IOError: ...
        """
        # Convert given lists to fd_set
        cdef fd_set rfds, wfds, xfds
            ^
------------------------------------------------------------

sage/ext/pselect.pyx:331:13: 'fd_set' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            n = get_fileno(f)
            if (n >= nfds): nfds = n + 1
            FD_SET(n, &xfds)

        cdef double tm
        cdef timespec tv
            ^
------------------------------------------------------------

sage/ext/pselect.pyx:352:13: 'timespec' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
            if (n >= nfds): nfds = n + 1
            FD_SET(n, &xfds)

        cdef double tm
        cdef timespec tv
        cdef timespec *ptv = NULL
            ^
------------------------------------------------------------

sage/ext/pselect.pyx:353:13: 'timespec' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int n
    try:
        n = f.fileno()
    except AttributeError:
        n = f
    if n < 0 or n >= FD_SETSIZE:
                              ^
------------------------------------------------------------

sage/ext/pselect.pyx:104:31: undeclared name not builtin: FD_SETSIZE

Error compiling Cython file:
------------------------------------------------------------
...
            ...
            IOError: ...
        """
        # Convert given lists to fd_set
        cdef fd_set rfds, wfds, xfds
        FD_ZERO(&rfds)
              ^
------------------------------------------------------------

sage/ext/pselect.pyx:332:15: undeclared name not builtin: FD_ZERO

Error compiling Cython file:
------------------------------------------------------------
...
        cdef int nfds = 0
        cdef int n
        for f in rlist:
            n = get_fileno(f)
            if (n >= nfds): nfds = n + 1
            FD_SET(n, &rfds)
                 ^
------------------------------------------------------------

sage/ext/pselect.pyx:341:18: undeclared name not builtin: FD_SET

Error compiling Cython file:
------------------------------------------------------------
...
                tm = 0
            tv.tv_sec = <long>tm
            tv.tv_nsec = <long>(1e9 * (tm - <double>tv.tv_sec))
            ptv = &tv

        ret = pselect(nfds, &rfds, &wfds, &xfds, ptv, &self.oldset)
                    ^
------------------------------------------------------------

sage/ext/pselect.pyx:363:21: undeclared name not builtin: pselect

Error compiling Cython file:
------------------------------------------------------------
...
                tm = 0
            tv.tv_sec = <long>tm
            tv.tv_nsec = <long>(1e9 * (tm - <double>tv.tv_sec))
            ptv = &tv

        ret = pselect(nfds, &rfds, &wfds, &xfds, ptv, &self.oldset)
                                                     ^
------------------------------------------------------------

sage/ext/pselect.pyx:363:54: Cannot convert 'sigset_t *' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        rready = []
        wready = []
        xready = []
        for f in rlist:
            n = get_fileno(f)
            if FD_ISSET(n, &rfds):
                      ^
------------------------------------------------------------

sage/ext/pselect.pyx:387:23: undeclared name not builtin: FD_ISSET
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 1015, in cythonize_one_helper
    return cythonize_one(*m)
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
CompileError: sage/ext/pselect.pyx
************************************************************************
Traceback (most recent call last):
  File "setup.py", line 604, in <module>
    run_cythonize()
  File "setup.py", line 596, in run_cythonize
    'profile': profile,
  File "/usr/lib64/python2.7/site-packages/Cython/Build/Dependencies.py", line 868, in cythonize
    result.get(99999)  # seconds
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
CompileError: sage/ext/pselect.pyx
************************************************************************
Error building the Sage library
************************************************************************
 * ERROR: sci-mathematics/sage-6.10::sage-on-gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_compile
 *   environment, line 4524:  Called distutils-r1_src_compile
 *   environment, line 1313:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  572:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3826:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2835:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2833:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  902:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1304:  Called distutils-r1_python_compile
 *   environment, line 1176:  Called esetup.py 'build'
 *   environment, line 1816:  Called die
 * The specific snippet of code:
 *       "${@}" || die "${die_args[@]}" || return ${?}
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/sage-6.10::sage-on-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/sage-6.10::sage-on-gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/sage-6.10/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/sage-6.10/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/sage-6.10/work/sage-6.10/src-python2_7'
 * S: '/var/tmp/portage/sci-mathematics/sage-6.10/work/sage-6.10/src'
```

[Here](http://paste2.org/M8IBEWxH) is my build.log file. Here is the output of `emerge --info`:
```bash
Portage 2.2.20 (python 2.7.9-final-0, default/linux/amd64/13.0/desktop, gcc-4.9.3, glibc-2.21-r1, 4.3.0-sabayon x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-4.3.0-sabayon-x86_64-Intel-R-_Core-TM-_i5-3230M_CPU_@_2.60GHz-with-gentoo-2.2
KiB Mem:    11864804 total,   1517644 free
KiB Swap:   13051492 total,  13024852 free
Timestamp of repository gentoo: Wed, 23 Dec 2015 21:15:01 +0000
sh bash 4.3_p39
ld GNU ld (Gentoo 2.25.1 p1.1) 2.25.1
app-shells/bash:          4.3_p39::gentoo
dev-java/java-config:     2.2.0::gentoo
dev-lang/perl:            5.20.2::gentoo
dev-lang/python:          2.7.9-r1::gentoo, 3.3.5-r1::gentoo, 3.4.3::gentoo
dev-util/cmake:           3.3.1-r1::gentoo
dev-util/pkgconfig:       0.29::gentoo
sys-apps/baselayout:      2.2-r1::sabayon-distro
sys-apps/openrc:          0.17::gentoo
sys-apps/sandbox:         2.9::gentoo
sys-devel/autoconf:       2.69::gentoo
sys-devel/automake:       1.11.6-r1::gentoo, 1.13.4::gentoo, 1.15::gentoo
sys-devel/binutils:       2.25.1-r1::gentoo
sys-devel/gcc:            4.9.3::sabayon-distro
sys-devel/gcc-config:     1.8-r1::sabayon-distro
sys-devel/libtool:        2.4.6::gentoo
sys-devel/make:           4.1-r1::gentoo
sys-kernel/linux-headers: 3.18::gentoo
sys-libs/glibc:           2.21-r1::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.europe.gentoo.org/gentoo-portage
    priority: -1000

user_defined
    location: /usr/local/portage
    masters: gentoo
    priority: 0

calculate
    location: /var/lib/layman/calculate
    masters: gentoo
    priority: 50

elementary
    location: /var/lib/layman/elementary
    masters: gentoo
    priority: 50

enlightenment
    location: /var/lib/layman/enlightenment
    masters: gentoo
    priority: 50

gnome
    location: /var/lib/layman/gnome
    masters: gentoo
    priority: 50

jorgicio
    location: /var/lib/layman/jorgicio
    masters: gentoo
    priority: 50

kde
    location: /var/lib/layman/kde
    masters: gentoo
    priority: 50

lisp
    location: /var/lib/layman/lisp
    masters: gentoo
    priority: 50

sabayon
    location: /var/lib/layman/sabayon
    masters: gentoo
    priority: 50

sabayon-distro
    location: /var/lib/layman/sabayon-distro
    masters: gentoo
    priority: 50

sabayon-tools
    location: /var/lib/layman/sabayon-tools
    masters: gentoo
    priority: 50

sage-on-gentoo
    location: /var/lib/layman/sage-on-gentoo
    masters: gentoo science
    priority: 50

science
    location: /var/lib/layman/science
    masters: gentoo
    priority: 50

unity-gentoo
    location: /var/lib/layman/unity-gentoo
    masters: gentoo
    priority: 50

Installed sets: @system
ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=x86-64 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /etc/conf.d /etc/entropy /etc/init.d /usr/share/config /usr/share/config/kdm /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php5.5/ext-active/ /etc/php/apache2-php5.6/ext-active/ /etc/php/cgi-php5.5/ext-active/ /etc/php/cgi-php5.6/ext-active/ /etc/php/cli-php5.5/ext-active/ /etc/php/cli-php5.6/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/skel /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c /lib/modules"
CXXFLAGS="-O2 -march=x86-64 -pipe"
DISTDIR="/usr/portage/distfiles"
FCFLAGS="-O2 -pipe"
FEATURES="assume-digests binpkg-logs compressdebug config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync news parallel-fetch preserve-libs protect-owned sandbox sfperms splitdebug strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-O2 -pipe"
GENTOO_MIRRORS="ftp://ftp.spline.inf.fu-berlin.de/mirrors/gentoo/ http://archive.mmu.edu.my/gentoo rsync://gentoo.bloodhost.ru/gentoo-distfiles ftp://gentoo.mirrors.tds.net/gentoo ftp://ftp.halifax.rwth-aachen.de/gentoo/ rsync://mirror.neolabs.kz/gentoo http://ftp.gentoo.bg/ http://ftp.cc.uoc.gr/mirrors/linux/gentoo/ ftp://ftp.cc.uoc.gr/mirrors/linux/gentoo/ ftp://mirrors.tera-byte.com/pub/gentoo"
LANG="en_GB.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j16 -s"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages"
PORTAGE_TMPDIR="/var/tmp"
USE="X a52 aac accessibility acl acpi aiglx aim alsa amd64 artswrappersuid audiofile avahi bash-completion berkdb bidi bluetooth bluray bzip2 cairo cdda cddb cdr cjk cli cpudetection cracklib crypt cups cxx dbus dga dri dts dv dvb dvd dvdr dvdread dvi emboss encode exif fam fame fat ffmpeg firefox flac foomatic-db fortran freetype gcj gdbm gif gimpprint glamor gmp gnutls gphoto2 gpm gsm gtk hfs iconv icq ieee1394 imap inotify ipod ipv6 irc irda jabber jack jfs joystick jpeg kdeenablefinal kdehiddenvisibility kerberos lame lcd lcms ldap libav libnotify live lm_sensors logind lzo mad mail matroska mjpeg mmx mmxext mng modules mozdevelop mp3 mp3rtp mp4 mpeg msn multilib musepack musicbrainz ncurses network nls nptl nsplugin ntfs ogg openal openexr opengl openmp pam pango pcmcia pcre pda pdf perl png policykit ppds pulseaudio python qt3support qt4 rar rdesktop readline real reiserfs rss scanner sdl seccomp session slp speex spell sse sse2 ssl startup-notification stream svg sysfs systemd tcpd theora tiff truetype udev udisks unicode upower usb v4l v4l2 visualization vorbis wifi win32codecs wmf wxwidgets x264 x265 xattr xcb xfs xine xinerama xml xpm xprint xulrunner xv xvid xvmc yahoo zeroconf zlib" ABI_X86="64 32" ALSA_CARDS="emu10k1x darla20 darla24 emu10k1 gina20 gina24 hdsp hdspm ice1712 indigo indigoio layla20 layla24 mia mixart mona pcxhr rme32 rme96 sb16 sbawe sscape usbusx2y vx222 usb-usx2y" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" APACHE2_MPMS="prefork" CALLIGRA_FEATURES="kexi words flow plan sheets stage tables krita karbon braindump author" CAMERAS="agfa_cl20 casio_qv dimagev dimera3500 kodak_dc120 kodak_dc210 kodak_dc240 kodak_dc3200 kodak_ez200 konica_qm150 panasonic_coolshot panasonic_dc1000 panasonic_dc1580 panasonic_l859 polaroid_pdc320 polaroid_pdc640 polaroid_pdc700 ricoh_g3 sipix_blink sipix_blink2 sipix_web2 sony_dscf1 sony_dscf55 toshiba_pdrm11 adc65 aox barbie canon clicksmart310 digigr8 digita directory enigma13 fuji gsmart300 hp215 iclick jamcam jd11 konica largan lg_gsm mars mustek pccam300 pccam600 ptp2 ricoh samsung sierra smal sonix soundvision spca50x sq905 stv0674 stv0680 sx330z template" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-32 efi-64 pc" INPUT_DEVICES="evdev void" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer pdfimport wiki-publisher" LINGUAS="en en_US af ar az bg bn br bs ca cs cy da de el en_GB eo es et eu fa fi fr fy ga gl he hi hr hu is it ja kk km ko lt lv mk mn ms nb nds nl nn pa pl pt pt_BR ro ru rw se sk sl sr sr@Latn ss sv ta tg tr uk uz vi zh_CN zh_TW es_AR es_ES fy_NL ga_IE gu gu_IN nb_NO nn_NO pt_PT sv_SE zh" LIRC_DEVICES="audio audio_alsa serial pctv" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-5" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7 python3_4" QEMU_SOFTMMU_TARGETS="x86_64 arm cris i386 m68k microblaze mips mips64 mips64el mipsel ppc ppc64 ppcemb sh4 sh4eb sparc sparc64" QEMU_USER_TARGETS="alpha arm armeb cris i386 m68k microblaze mips mipsel ppc ppc64 ppc64abi32 sh4 sh4eb sparc sparc32plus sparc64 x86_64" RUBY_TARGETS="ruby20" USERLAND="GNU" VIDEO_CARDS="fbdev vesa radeonsi radeon nouveau" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
USE_PYTHON="2.7"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

while here is the output of `emerge -pqv...`:
```bash
[ebuild  N    ] sci-mathematics/sage-6.10  USE="X bin-html -bin-pdf -bliss -debug -html -latex -modular_decomposition -pdf -testsuite" LINGUAS="ca de en fr hu it pt ru tr" PYTHON_TARGETS="python2_7" 
[ebuild  N    ] sci-mathematics/sage-notebook-0.11.4-r4  USE="java -server {-test}" PYTHON_TARGETS="python2_7" 
```

**Comment by fusion809** [comment]
Never mind, turned out to be an Cython issue that was fixed by remerging Cython.
