### ISSUE TITLE
AttributeError in building html-docs

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#388]
I've been off the grid for about a week. The linker in my Prefix somehow got broken and I had to reinstall everything from scratch. This is a Prefix with its on glibc. I now have two packages left to complete building sage-9999; sage and sage-notebook and sage fails in building the html-docs in multiple places as
```
# Sphinx version: 1.2.2
# Python version: 2.7.10
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Loaded extensions:
Traceback (most recent call last):
  File "/storage/strogdon/gentoo-prefix/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 253, in main
    warningiserror, tags, verbosity, parallel)
  File "/storage/strogdon/gentoo-prefix/usr/lib/python2.7/site-packages/sphinx/application.py", line 107, in __init__
    confoverrides or {}, self.tags)
  File "/storage/strogdon/gentoo-prefix/usr/lib/python2.7/site-packages/sphinx/config.py", line 229, in __init__
    execfile_(filename, config)
  File "/storage/strogdon/gentoo-prefix/usr/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 105, in execfile_
    exec code in _globals
  File "conf.py", line 17, in <module>
    # ---------------------
  File "/storage/strogdon/gentoo-prefix/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/doc/common/conf.py", line 232, in <module>
    sagenb_path = working_set.find(Requirement.parse('sagenb')).location
AttributeError: 'NoneType' object has no attribute 'location'
```
A grep of `sagenb` from the build log gives
```
copying sage/repl/rich_output/backend_sagenb.py -> /storage/strogdon/gentoo-prefix/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/lib/sage/repl/rich_output
[arithgrou] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[tensor_fr] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[homology ] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[dynamics ] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[asymptoti] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[calculus ] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[categorie] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[algebras ] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
[polynomia] sagenb_path = working_set.find(Requirement.parse('sagenb')).location
```
Here `sage-notebook` is the last package to be installed. Is it possible that `sage-notebook` needs to be installed prior to building the html-docs. It's late here and I will investigate tomorrow.

**Comment by kiwifb** [comment]
Totally possible. I think I have seen stuff upstream. This is also totally annoying. Looking.

**Comment by kiwifb** [comment]
https://github.com/sagemath/sage/blob/develop/build/make/deps#L188 is our clue. Some bits in `doc/common/conf.py` should be patchable. Others in `doc/en/reference/notebook/index.rst` have been present for years without causing concerns. Still there is the spectre of a circular dependency lurking.

**Comment by kiwifb** [comment]
Everything has been there for years without trouble. Something triggered this and will need to be fixed at last. It may be related to our overproduction of font files actually.

**Comment by kiwifb** [comment]
Committed some dependency changes so that sagenb is installed first instead of last. I think it is now safe to install it first. `setup.py` doesn't require any parts of `sage` so it should be ok.

**Comment by kiwifb** [comment]
Actually I may end up putting `sage` in `PDEPEND` for `sagenb` the reverse from what it has been for the last few years.

**Comment by strogdon** [comment]
Yes, circular dependencies
```
[nomerge       ] sci-mathematics/sage-9999::sage-on-gentoo  USE="debug html pdf testsuite -X -bliss -latex -modular_decomposition" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 
[ebuild  N     ]  sci-mathematics/sage-notebook-0.11.6.1::sage-on-gentoo  USE="java -server {-test}" PYTHON_TARGETS="python2_7" 0 KiB
[ebuild  N    #]   sci-mathematics/sage-9999::sage-on-gentoo  USE="debug html pdf testsuite -X -bliss -latex -modular_decomposition" LINGUAS="en -ca -de -fr -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python2_7" 0 KiB

Total: 2 packages (2 new), Size of downloads: 0 KiB

 * Error: circular dependencies:

(sci-mathematics/sage-notebook-0.11.6.1:0/0::sage-on-gentoo, ebuild scheduled for merge) depends on
 (sci-mathematics/sage-9999:0/0::sage-on-gentoo, ebuild scheduled for merge) (runtime)
  (sci-mathematics/sage-notebook-0.11.6.1:0/0::sage-on-gentoo, ebuild scheduled for merge) (buildtime)

It might be possible to break this cycle
by applying the following change:
- sci-mathematics/sage-9999 (Change USE: -html -testsuite -pdf)

Note that this change can be reverted, once the package has been installed.
```
This may not be easy to resolve. And probably only manifests itself on fresh install of everything. I'm reasonably sure the suggested fix (`USE: -html -testsuite -pdf`) would temporarily fix things.

**Comment by kiwifb** [comment]
OK I'll move `sage` to `PDEPEND` in `sagenb` and see what happens.

**Comment by kiwifb** [comment]
Pushed.

**Comment by strogdon** [comment]
OK, so this fixed things here. And perhaps my Prefix is operational again!
