### ISSUE TITLE
Can't test on sage 7

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#394]
`sage -t -a` fails with

```                                                                                          
no stored timings available
Running doctests with ID 2016-02-06-01-14-20-20a126df.
Using --optional=optional,sage
Doctesting entire Sage library.
Doctesting 3139 files.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/sage-runtests", line 88, in <module>
    err = DC.run()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 953, in run
    self.run_doctests()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 680, in run_doctests
    self.dispatcher = DocTestDispatcher(self)
  File "/usr/lib/python2.7/site-packages/sage/doctest/forker.py", line 1379, in __init__
    init_sage()
  File "/usr/lib/python2.7/site-packages/sage/doctest/forker.py", line 128, in init_sage
    from sympy.printing.pretty.stringpict import stringPict
  File "/usr/lib/python2.7/site-packages/sympy/__init__.py", line 37, in <module>
    from .core import *
  File "/usr/lib/python2.7/site-packages/sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr
  File "/usr/lib/python2.7/site-packages/sympy/core/expr.py", line 7, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 9, in <module>
    import sympy.mpmath.libmp as libmp
  File "/usr/lib/python2.7/site-packages/sympy/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/usr/lib/python2.7/site-packages/sympy/mpmath/ctx_mp.py", line 47, in <module>
    from sage.libs.mpmath.ext_main import Context as BaseMPContext
  File "sage/libs/mpmath/ext_main.pyx", line 34, in init sage.libs.mpmath.ext_main (/var/tmp/portage/sci-mathematics/sage-7.0/work/sage-7.0/src-python2_7/build/cythonized/sage/libs/mpmath/ext_main.c:33230)
  File "/usr/lib/python2.7/site-packages/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/usr/lib/python2.7/site-packages/mpmath/ctx_mp.py", line 49, in <module>
    import sage.libs.mpmath.ext_main as _mpf_module
AttributeError: 'module' object has no attribute 'ext_main'

``

**Comment by kiwifb** [comment]
Version of `python`?

**Comment by Alessandro-Barbieri** [comment]
2.7.10

**Comment by kiwifb** [comment]
I should have been more specific `2.7.10-r?`?

**Comment by Alessandro-Barbieri** [comment]
python --version outputs exactly Python 2.7.10

eix-installed tells me that I have dev-lang/python-2.7.10-r1

**Comment by kiwifb** [comment]
On 02/09/16 05:06, Alessandro Barbieri wrote:
> python --version outputs exactly Python 2.7.10
>
> eix-installed tells me that I have dev-lang/python-2.7.10-r1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cschwan/sage-on-gentoo/issues/394#issuecomment-181421484>.
>
OK, upgrade to 2.7.10-r10 from the overlay. It should be unmasked.

Francois

**Comment by Alessandro-Barbieri** [comment]
Now i have

`sage -t all                                                                                                              
no stored timings available
Running doctests with ID 2016-02-09-18-53-57-86f9853f.
Using --optional=optional,sage
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/sage-runtests", line 88, in <module>
    err = DC.run()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 950, in run
    self.expand_files_into_sources()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 565, in expand_files_into_sources
    self.sources = [FileDocTestSource(path, self.options) for path in expand()]
  File "/usr/lib/python2.7/site-packages/sage/doctest/sources.py", line 494, in __init__
    raise ValueError("unknown file extension %r"%ext)
ValueError: unknown file extension ''
`

**Comment by kiwifb** [comment]
Hum... the only thing I can think of is that `cython` and then `sage` have to be rebuilt but you have put your finger on something that someone with a system with `sage` for a long while may have missed.

**Comment by strogdon** [comment]
I just saw this. Perhaps try `sage -t -all` or `sage -t --all`.

**Comment by kiwifb** [comment]
Thanks Steve I had missed that. Definitely `sage -t --all`

**Comment by Alessandro-Barbieri** [comment]
Re emerged cython and sage, `sage -t --all` give me the same error as the first I reported.

**Comment by kiwifb** [comment]
OK I can reproduce the error with `sage -t all` because what happens is `sage` tries to run doctest on a file named `all` which doesn't exist. But `sage -t --all` should give trouble...
What happens when you try `sage --testall`?

**Comment by Alessandro-Barbieri** [comment]
`
sage --testall
no stored timings available
Running doctests with ID 2016-02-11-01-41-08-4e4b80b6.
Using --optional=optional,sage
Doctesting entire Sage library.
Doctesting 3139 files.
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/sage-runtests", line 88, in <module>
    err = DC.run()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 953, in run
    self.run_doctests()
  File "/usr/lib/python2.7/site-packages/sage/doctest/control.py", line 680, in run_doctests
    self.dispatcher = DocTestDispatcher(self)
  File "/usr/lib/python2.7/site-packages/sage/doctest/forker.py", line 1379, in __init__
    init_sage()
  File "/usr/lib/python2.7/site-packages/sage/doctest/forker.py", line 128, in init_sage
    from sympy.printing.pretty.stringpict import stringPict
  File "/usr/lib/python2.7/site-packages/sympy/__init__.py", line 37, in <module>
    from .core import *
  File "/usr/lib/python2.7/site-packages/sympy/core/__init__.py", line 8, in <module>
    from .expr import Expr, AtomicExpr
  File "/usr/lib/python2.7/site-packages/sympy/core/expr.py", line 7, in <module>
    from .evalf import EvalfMixin, pure_complex
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 9, in <module>
    import sympy.mpmath.libmp as libmp
  File "/usr/lib/python2.7/site-packages/sympy/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/usr/lib/python2.7/site-packages/sympy/mpmath/ctx_mp.py", line 47, in <module>
    from sage.libs.mpmath.ext_main import Context as BaseMPContext
  File "sage/libs/mpmath/ext_main.pyx", line 34, in init sage.libs.mpmath.ext_main (/var/tmp/portage/sci-mathematics/sage-7.0/work/sage-7.0/src-python2_7/build/cythonized/sage/libs/mpmath/ext_main.c:33230)
  File "/usr/lib/python2.7/site-packages/mpmath/__init__.py", line 6, in <module>
    from .ctx_mp import MPContext
  File "/usr/lib/python2.7/site-packages/mpmath/ctx_mp.py", line 49, in <module>
    import sage.libs.mpmath.ext_main as _mpf_module
AttributeError: 'module' object has no attribute 'ext_main'

`

**Comment by kiwifb** [comment]
I am betting you have `sympy` from the main tree installed instead of the one from the overlay. `emerge -1v sympy` should be sufficient to make this problem go away. I didn't think of this scenario of installation I may have to bump `sympy`'s version in the overlay.

**Comment by Alessandro-Barbieri** [comment]
Re emerged scipy and now I'm testing.
