### ISSUE TITLE
sage-notebook fails to start

### ISSUE THREAD

**Issue by atlaua** [cschwan/sage-on-gentoo#396]
I've just merged sage-7.0 and sage-notebook-0.11.7. Sage itself seems to work, but the notebook() interface fails:

```
aranea@gentp ~ $ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath Version 7.0, Release Date: 2016-01-19                     │
│ Type "notebook()" for the browser-based notebook interface.        │
│ Type "help()" for help.                                            │
└────────────────────────────────────────────────────────────────────┘
sage: print SAGE_LOCAL
/usr/
sage: notebook()
cannot import name SAGE_DOC_SRC
Sphinx docstrings not available.
The notebook files are stored in: sage_notebook.sagenb
┌────────────────────────────────────────────────┐
│                                                │
│ Open your web browser to http://localhost:8080 │
│                                                │
└────────────────────────────────────────────────┘
Executing twistd  --pidfile="sage_notebook.sagenb/sagenb.pid" -ny "sage_notebook.sagenb/twistedconf.tac"
cannot import name SAGE_DOC_SRC
Sphinx docstrings not available.
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "sage_notebook.sagenb/twistedconf.tac", line 18, in <module>
    flask_app = flask_base.create_app("/home/aranea/.sage/sage_notebook.sagenb",interface="localhost",port=8080,secure=False, **opts)
  File "/usr/lib64/python2.7/site-packages/sagenb/flask_version/base.py", line 420, in create_app
    template_folder=TEMPLATE_PATH)
  File "/usr/lib64/python2.7/site-packages/sagenb/flask_version/base.py", line 39, in __init__
    self.add_static_path('/java/jmol', os.path.join(SAGE_LOCAL,"share","sage-jmol-bin","lib"))
exceptions.NameError: global name 'SAGE_LOCAL' is not defined

Failed to load application: global name 'SAGE_LOCAL' is not defined

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-2-3728cb3d7c7d> in <module>()
----> 1 notebook()

/usr/lib64/python2.7/site-packages/sage/misc/lazy_import.pyx in sage.misc.lazy_import.LazyImport.__call__ (/var/tmp/portage/sci-mathematics/sage-7.0/work/sage-7.0/src-python2_7/build/cythonized/sage/misc/lazy_import.c:3561)()
    384             True
    385         """
--> 386         return self._get_object()(*args, **kwds)
    387 
    388     def __repr__(self):

/usr/lib64/python2.7/site-packages/sagenb/notebook/notebook_object.pyc in __call__(self, *args, **kwds)
    237     """
    238     def __call__(self, *args, **kwds):
--> 239         return self.notebook(*args, **kwds)
    240 
    241     notebook = run_notebook.notebook_run

/usr/lib64/python2.7/site-packages/sagenb/notebook/run_notebook.pyc in notebook_run(self, directory, port, interface, port_tries, secure, reset, accounts, openid, server_pool, ulimit, timeout, doc_timeout, upload, automatic_login, start_path, fork, quiet, server, profile, subnets, require_login, open_viewer, address)
    638     os.chdir(cwd)
    639     if e == 256:
--> 640         raise socket.error
    641 
    642 def get_admin_passwd():

error: 
sage: 
Exiting Sage (CPU time 0m0.62s, Wall time 0m18.98s).
```

**Comment by kiwifb** [comment]
I'll have to check how I enforce the dependencies but `sage-notebook-0.11.7` is meant to be used with `sage-7.1` and after not 7.0 or before.

**Comment by kiwifb** [comment]
OK I did some changes to dependencies so from now on `sage-notebook` is fixed depending on the version of sage. You may have to re-emerge `sage-7.0` for it to kick in.

**Comment by atlaua** [comment]
Thanks, downgrading to sage-notebook-0.11.6.1 fixed the issue.
