### ISSUE TITLE
where is sphinx_plot for sage 7.1.beta6

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#402]
Lots of failed doctests in 7.1.beta6
```
sage -t --long --warn-long 96.0 /usr/share/doc/sage/html/en/reference/combinat/sage/combinat/dyck_word-1.py
    NameError in doctesting framework
**********************************************************************
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 2139, in __call__
    doctests, extras = self.source.create_doctests(sage_namespace)
  File "/usr/lib64/python2.7/site-packages/sage/doctest/sources.py", line 665, in create_doctests
    load(filename, namespace) # errors raised here will be caught in DocTestTask
  File "/usr/lib64/python2.7/site-packages/sage/repl/load.py", line 271, in load
    exec(code, globals)
  File "./dyck_word-1.py", line 2, in <module>
NameError: name 'sphinx_plot' is not defined
```

**Comment by kiwifb** [comment]
Those python files shouldn't be installed.

**Comment by kiwifb** [comment]
Those files should live in the `inventory` folder which isn't installed.
