### ISSUE TITLE
Issue with {lib}gap-4.8.3 in doctest

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#412]
The following two doctest fail
```
fbissey@QCD-nzi3 ~ $ sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py
too many failed tests, not using stored timings
Running doctests with ID 2016-04-05-13-43-08-94a65fdc.
Using --optional=optional,sage
Doctesting 1 file.
sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py", line 10, in sage.libs.gap.all_documented_functions
Failed example:
    DihedralGroup(8)
Expected:
    <pc group of size 8 with 3 generators>
Got:
    Dihedral group of order 16 as a permutation group
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py", line 12, in sage.libs.gap.all_documented_functions
Failed example:
    GeneratorsOfGroup(_)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 499, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 861, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.gap.all_documented_functions[2]>", line 1, in <module>
        GeneratorsOfGroup(_)
    NameError: name 'GeneratorsOfGroup' is not defined
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py", line 14, in sage.libs.gap.all_documented_functions
Failed example:
    List(_, Order)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 499, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 861, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.gap.all_documented_functions[3]>", line 1, in <module>
        List(_, Order)
    NameError: name 'Order' is not defined
**********************************************************************
1 item had failures:
   3 of   5 in sage.libs.gap.all_documented_functions
    [4 tests, 3 failures, 2.69 s]
----------------------------------------------------------------------
sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/all_documented_functions.py  # 3 doctests failed
----------------------------------------------------------------------
Total time for all tests: 2.7 seconds
    cpu time: 0.8 seconds
    cumulative wall time: 2.7 seconds
```
and
```
fbissey@QCD-nzi3 ~ $ sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/assigned_names.py
too many failed tests, not using stored timings
Running doctests with ID 2016-04-05-13-44-55-1dec1f68.
Using --optional=optional,sage
Doctesting 1 file.
sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/assigned_names.py
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/libs/gap/assigned_names.py", line 11, in sage.libs.gap.assigned_names
Failed example:
    'SubdirectProduct' in FUNCTIONS
Expected:
    True
Got:
    False
**********************************************************************
File "/usr/lib64/python2.7/site-packages/sage/libs/gap/assigned_names.py", line 133, in sage.libs.gap.assigned_names.list_functions
Failed example:
    'SubdirectProduct' in FUNCTIONS    # indirect doctest
Expected:
    True
Got:
    False
**********************************************************************
2 items had failures:
   1 of   5 in sage.libs.gap.assigned_names
   1 of   4 in sage.libs.gap.assigned_names.list_functions
    [15 tests, 2 failures, 0.37 s]
----------------------------------------------------------------------
sage -t --long /usr/lib64/python2.7/site-packages/sage/libs/gap/assigned_names.py  # 2 doctests failed
----------------------------------------------------------------------
Total time for all tests: 0.4 seconds
    cpu time: 0.4 seconds
    cumulative wall time: 0.4 seconds
```
Reason unknown so far. All other gap related test pass.

**Comment by kiwifb** [comment]
Mysteriously disappeared.

**Comment by kiwifb** [comment]
Closing for now.
