### ISSUE TITLE
html-docs (8.1.beta5) fail to build on gentoo

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#487]
Now I do have another gentoo box where the html-docs do build. It may be parallel build related although it doesn't appear to be. I will restart the build tomorrow. vanilla does build on this computer.
```
[reference] lfunctions: 2 todos, 5 index, 0 citations, 4 modules
[reference] libs: 1 todos, 41 index, 0 citations, 40 modules
[reference] logic: 2 todos, 7 index, 0 citations, 6 modules
[reference] Exception occurred:
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/multidocs.py", line 121, in get_env
[reference] docenv = cPickle.load(f)
[reference] BadPickleGet: 671089860
[reference] The full traceback has been saved in /var/tmp/portage/sci-mathematics/sage-9999/temp/sphinx-err-MTPU_F.log, if you want to report the issue to the developers.
[reference] Please also report this if it was a user error, so that a better error message can be provided next time.
[reference] A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "sage_setup/docbuild/__main__.py", line 2, in <module>
    main()
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 1675, in main
    builder()
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 310, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 512, in _wrapper
    getattr(DocBuilder(self.name, lang), format)(*args, **kwds)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 105, in f
    runsphinx()
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/sphinxbuild.py", line 218, in runsphinx
    raise exception
OSError: [reference] Exception occurred:

[reference] WARNING: Error building the documentation.
[reference] Traceback (most recent call last):
[reference] File "sage_setup/docbuild/__main__.py", line 2, in <module>
[reference] main()
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 1675, in main
[reference] builder()
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 310, in _wrapper
[reference] getattr(get_builder(document), 'inventory')(*args, **kwds)
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 512, in _wrapper
[reference] getattr(DocBuilder(self.name, lang), format)(*args, **kwds)
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/__init__.py", line 105, in f
[reference] runsphinx()
[reference] File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/sphinxbuild.py", line 218, in runsphinx
[reference] raise exception
[reference] OSError: [reference] Exception occurred:
```

**Comment by kiwifb** [comment]
Pickle again. What does `/var/tmp/portage/sci-mathematics/sage-9999/temp/sphinx-err-MTPU_F.log` says?

**Comment by strogdon** [comment]
I've found these log files to not be very useful. But maybe I'm not looking at the right thing.
```
# Sphinx version: 1.6.3
# Python version: 2.7.12 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.9.5
# Last messages:
#   lfunctions:
#   2 todos, 5 index, 0 citations
#   , 4 modules
#   libs:
#   1 todos, 41 index, 0 citations
#   , 40 modules
#   logic:
#   2 todos, 7 index, 0 citations
#   , 6 modules
#   manifolds:
# Loaded extensions:
#   sphinx.ext.inheritance_diagram (1.6.3) from /usr/lib64/python2.7/site-packages/sphinx/ext/inheritance_diagram.pyc
#   sphinx.ext.mathjax (1.6.3) from /usr/lib64/python2.7/site-packages/sphinx/ext/mathjax.pyc
#   inventory_builder (unknown version) from /var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/inventory_builder.py
#   multidocs (unknown version) from /var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/multidocs.py
#   sage_autodoc (1.6.3) from /var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/sage_autodoc.py
#   sphinx.ext.todo (1.6.3) from /usr/lib64/python2.7/site-packages/sphinx/ext/todo.pyc
#   sphinx.ext.graphviz (1.6.3) from /usr/lib64/python2.7/site-packages/sphinx/ext/graphviz.pyc
#   matplotlib.sphinxext.plot_directive (unknown version) from /usr/lib64/python2.7/site-packages/matplotlib/sphinxext/plot_directive.pyc
#   alabaster (0.7.9) from /usr/lib64/python2.7/site-packages/alabaster/__init__.pyc
#   sphinx.ext.extlinks (1.6.3) from /usr/lib64/python2.7/site-packages/sphinx/ext/extlinks.pyc
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib64/python2.7/site-packages/sphinx/environment/__init__.py", line 589, in update
    for retval in self.app.emit('env-updated', self):
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/usr/lib64/python2.7/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/multidocs.py", line 52, in merge_environment
    docenv = get_env(app, curdoc)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/sage_setup/docbuild/ext/multidocs.py", line 121, in get_env
    docenv = cPickle.load(f)
BadPickleGet: 671089860
```

**Comment by strogdon** [comment]
Rebuilding sage was successful and the html-docs were generated. This is an older machine and generating the html-docs is taking increasingly longer and longer. Perhaps the failure to build the docs is a symptom of what's to come.

**Comment by kiwifb** [comment]
How much ram?

**Comment by strogdon** [comment]
8 GB of ram which is at the boundary, from what I understand, of what is needed. It never uses a 8 gig, maybe 7. I try to shut down memory hogs like browsers when it's being built.

**Comment by kiwifb** [comment]
My mac manages with 8GB. The number of processes may have an impact too. My mac maxes at 2 processes.

**Comment by strogdon** [comment]
Mine has 4 cpus but it's slow. Actually vanilla builds with more ease than sage-on-gentoo, but there the builds are always incremental.

**Comment by kiwifb** [comment]
I am closing this as obsolete. May be the more recent issue is another incarnation of this.

**Comment by strogdon** [comment]
Oddly I saw this again today (8.3.rc0). It was on a laptop. The original failure was on a desktop. Restarting seemed to fix things.
