### ISSUE TITLE
IOError when doctesting singular-related tests in 8.9.beta5

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#545]
The failures
```
sage -t --long usr/lib64/python2.7/site-packages/sage/libs/singular/function.pyx
**********************************************************************
File "usr/lib64/python2.7/site-packages/sage/libs/singular/function.pyx", line 1338, in sage.libs.singular.function.SingularFunction._instancedoc_
Failed example:
    'groebner' in groebner.__doc__
Exception raised:
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.singular.function.SingularFunction._instancedoc_[2]>", line 1, in <module>
        'groebner' in groebner.__doc__
      File "sage/docs/instancedoc.pyx", line 212, in sage.docs.instancedoc.InstanceDocDescriptor.__get__ (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/docs/instancedoc.c:1779)
        return self.instancedoc(obj)
      File "sage/libs/singular/function.pyx", line 1387, in sage.libs.singular.function.SingularFunction._instancedoc_ (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/libs/singular/function.cpp:15059)
        singular_doc = get_docstring(self._name).split('\n')
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2314, in get_docstring
        generate_docstring_dictionary()
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2274, in generate_docstring_dictionary
        encoding='latin-1') as f:
    IOError: [Errno 2] No such file or directory: '/storage/strogdon/gentoo-rap/usr/share/sage/singular/../info/singular.hlp'
**********************************************************************
```
and
```
sage -t --long usr/lib64/python2.7/site-packages/sage/libs/singular/function.pyx
**********************************************************************
File "usr/lib64/python2.7/site-packages/sage/libs/singular/function.pyx", line 1338, in sage.libs.singular.function.SingularFunction._instancedoc_
Failed example:
    'groebner' in groebner.__doc__
Exception raised:
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.libs.singular.function.SingularFunction._instancedoc_[2]>", line 1, in <module>
        'groebner' in groebner.__doc__
      File "sage/docs/instancedoc.pyx", line 212, in sage.docs.instancedoc.InstanceDocDescriptor.__get__ (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/docs/instancedoc.c:1779)
        return self.instancedoc(obj)
      File "sage/libs/singular/function.pyx", line 1387, in sage.libs.singular.function.SingularFunction._instancedoc_ (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/libs/singular/function.cpp:15059)
        singular_doc = get_docstring(self._name).split('\n')
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2314, in get_docstring
        generate_docstring_dictionary()
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2274, in generate_docstring_dictionary
        encoding='latin-1') as f:
    IOError: [Errno 2] No such file or directory: '/storage/strogdon/gentoo-rap/usr/share/sage/singular/../info/singular.hlp'
**********************************************************************
```

**Comment by kiwifb** [comment]
Ok, now I see the problem properly. There is a small issue with sage-8.9-env.patch. I should have corrected the new `SINGULARPATH` variable for sage-on-gentoo. I'll do that when I can. This is a busy time right now.

**Comment by strogdon** [comment]
The second doctest is the same as the first. The second should be 
```
sage -t --long usr/lib64/python2.7/site-packages/sage/interfaces/singular.py
**********************************************************************
File "usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2180, in sage.interfaces.singular.SingularFunction._instancedoc_
Failed example:
    'groebner' in singular.groebner.__doc__
Exception raised:
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 681, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/doctest/forker.py", line 1105, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.interfaces.singular.SingularFunction._instancedoc_[0]>", line 1, in <module>
        'groebner' in singular.groebner.__doc__
      File "sage/docs/instancedoc.pyx", line 212, in sage.docs.instancedoc.InstanceDocDescriptor.__get__ (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python2_7/build/cythonized/sage/docs/instancedoc.c:1779)
        return self.instancedoc(obj)
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2184, in _instancedoc_
        generate_docstring_dictionary()
      File "/storage/strogdon/gentoo-rap/usr/lib64/python2.7/site-packages/sage/interfaces/singular.py", line 2274, in generate_docstring_dictionary
        encoding='latin-1') as f:
    IOError: [Errno 2] No such file or directory: '/storage/strogdon/gentoo-rap/usr/share/sage/singular/../info/singular.hlp'
**********************************************************************
```
The are 5 such failures in the doctest.

**Comment by kiwifb** [comment]
Ok, sync, rebuild and try again.

**Comment by strogdon** [comment]
Good here.
