### ISSUE TITLE
jupyter_core and secure_write ImportError

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#569]
Building the html doc I see
```
[repl     ] WARNING: autodoc: failed to import module 'interact' from module 'sage.repl.ipython_kernel'; the following exception was raised:
[repl     ] cannot import name 'secure_write'
[repl     ] WARNING: autodoc: failed to import module 'kernel' from module 'sage.repl.ipython_kernel'; the following exception was raised:
[repl     ] cannot import name 'secure_write'
[repl     ] WARNING: autodoc: failed to import module 'widgets' from module 'sage.repl.ipython_kernel'; the following exception was raised:
[repl     ] cannot import name 'secure_write'
[repl     ] WARNING: autodoc: failed to import module 'widgets_sagenb' from module 'sage.repl.ipython_kernel'; the following exception was raised:
[repl     ] cannot import name 'secure_write'
[repl     ] The inventory files are in ../../build_doc/inventory/en/reference/repl.
Error building the documentation.
Traceback (most recent call last):
  File "sage_setup/docbuild/__main__.py", line 2, in <module>
    main()
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/__init__.py", line 1720, in main
    builder()
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/__init__.py", line 327, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/__init__.py", line 552, in _wrapper
    self._build_everything_except_bibliography(lang, format, *args, **kwds)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/__init__.py", line 538, in _build_everything_except_bibliography
    build_many(build_ref_doc, non_references)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/__init__.py", line 280, in build_many
    _build_many(target, args, processes=NUM_THREADS)
  File "/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_6/sage_setup/docbuild/utils.py", line 283, in build_many
    raise worker_exc.original_exception
OSError: WARNING: autodoc: failed to import module 'interact' from module 'sage.repl.ipython_kernel'; the following exception was raised:
```
To fix this I had to install `jupyter_core-4.6.1`. I believe >=4.6.0 is needed. I'm not sure about the sequence of things but I had `ipykernel-4.8.2` installed and it could not be rebuilt until `jupyter_core-4.6.1` was installed. I would get a `secure_write` ImportError. I can provide further details when Sage finishes building.

**Comment by kiwifb** [comment]
I am on `ipykernel-4.6.1-r1` and `jupyter_core-4.4.0`. I should change the keyword file. The reason I don't have a later `ipykernel` is that `4.8.2` doesn't have `python3_7` support (but `4.6.1-r1` does). So I guess  what you see is two packages that need to be upgraded together.

**Comment by kiwifb** [comment]
Now `ipykernel-4.8.2` should not be offered to you by default by the sage keywords. I guess I left it in the last clean up because I didn't realise it needed a new `jupyter_core` to go with it.

**Comment by strogdon** [comment]
From my Prefix with `jupyter_core-4.4.0` installed and building `ipykernel-4.6.1-r2` I get
```
>>> Compiling source in /storage/strogdon/gentoo-rap/var/tmp/portage/dev-python/ipykernel-4.6.1-r2/work/ipykernel-4.6.1 ...
 ^[[32;01m*^[[0m python3_6: running distutils-r1_run_phase distutils-r1_python_compile
python3.6 setup.py build
Traceback (most recent call last):
  File "setup.py", line 91, in <module>
    from ipykernel.kernelspec import write_kernel_spec, make_ipkernel_cmd, KERNEL_NAME
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/dev-python/ipykernel-4.6.1-r2/work/ipykernel-4.6.1/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/dev-python/ipykernel-4.6.1-r2/work/ipykernel-4.6.1/ipykernel/connect.py", line 18, in <module>
    import jupyter_client
  File "/storage/strogdon/gentoo-rap/usr/lib64/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/storage/strogdon/gentoo-rap/usr/lib64/python3.6/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write'
```
Has something changed between `-r1` and `-r2` or is something else up?

**Comment by kiwifb** [comment]
Which version of `jupyter_client` do you have? It is the package making the call.

**Comment by kiwifb** [comment]
Must be `jupyter_client`, I have a local mask for version over 5.3. It should be properly keyworded.

**Comment by strogdon** [comment]
Perhaps, I have `jupyter_client-5.3.4` installed. This stuff is tricky.

**Comment by strogdon** [comment]
I also have `jupyter_client-5.3.4` installed on Gentoo.

**Comment by kiwifb** [comment]
Keywords changed so `jupyter_client-5.3+` is not an option by default.

**Comment by strogdon** [comment]
OK this fixes things here.
