### ISSUE TITLE
sage-9.2.beta1 ValueError building html-docs in Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#590]
```
[plotting ] /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7/build/lib/sage/plot/contour_plot.py:docstring of sage.plot.contour_plot.contour_plot:438: WARNING: Exception occurred in plotting contour_plot-24
[plotting ]  from /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7/doc/en/reference/plotting/sage/plot/contour_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/matplotlib/sphinxext/plot_directive.py", line 484, in run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 4, in <module>
[plotting ]   File "<string>", line 32, in sphinx_plot
[plotting ]   File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7/build/lib/sage/plot/graphics.py", line 2776, in matplotlib
[plotting ]     g._render_on_subplot(subplot)
[plotting ]   File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7/build/lib/sage/plot/contour_plot.py", line 222, in _render_on_subplot
[plotting ]     cb = colorbar.Colorbar(cax, CSF, **kwds)
[plotting ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/matplotlib/colorbar.py", line 1220, in __init__
[plotting ]     ColorbarBase.__init__(self, ax, **kw)
[plotting ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/matplotlib/colorbar.py", line 459, in __init__
[plotting ]     ['uniform', 'proportional'], spacing=spacing)
[plotting ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 2145, in _check_in_list
[plotting ]     .format(v, k, ', '.join(map(repr, values))))
[plotting ] ValueError: None is not a valid value for spacing; supported values are 'uniform', 'proportional'
```
I have 6 of these ` WARNING:` followed by a `ValueError:` with a final
```
OSError: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_7/build/lib/sage/plot/contour_plot.py:docstring of sage.plot.contour_plot.contour_plot:438: WARNING: Exception occurred in plotting contour_plot-24
```
Since this is Prefix I could have some mismatch somewhere.

**Comment by kiwifb** [comment]
A bit of an issue, I pushed my changes for 9.2.beta1 but it is not yet on github. So, right now you are pulling sources for 9.2.beta0 instead of beta1. Which is sure to cause issues.

**Comment by strogdon** [comment]
And I new that because because I had pulled from vanilla without success. Never thought it would affect things here but didn't reason through things.

**Comment by kiwifb** [comment]
9.2.beta1 is supposed to come with MPL-3.2.1 by default but 9.2.beta0 is still on 2.2.x. So I removed the MPL-3.x patches for 9.2.beta1. You are most certainly getting hit by that.

**Comment by strogdon** [comment]
develop is now at `beta1`. This now builds, so we're OK.
