### ISSUE TITLE
doctest/test.py failures (9.2.beta12)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#597]
I have rebuilt vanilla using all available gentoo packages that vanilla will allow. Doctesting as
```
sage -tp 5 --long --all --memlimit=0
```
I have one failure that also fails on gentoo. This is the vanilla failure
```
sage -t --long --warn-long 153.4 --random-seed=0 src/sage/doctest/test.py
**********************************************************************
File "src/sage/doctest/test.py", line 521, in sage.doctest.test
Failed example:
    if system() == "Linux":
        P = subprocess.Popen(["sage", "-t", "--warn-long", "0", "--random-seed=0", "--memlimit=2000", "memlimit.rst"], stdout=subprocess.PIPE, **kwds)
        out, err = P.communicate()
        ok = ("MemoryError: failed to allocate" in bytes_to_str(out))
Expected nothing
Got:
    Traceback (most recent call last):
      File "/local/sage-git/sage/src/bin/sage-runtests", line 182, in <module>
        err = DC.run()
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/control.py", line 1230, in run
        self.run_doctests()
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/control.py", line 926, in run_doctests
        self.dispatcher = DocTestDispatcher(self)
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/forker.py", line 1670, in __init__
        init_sage(controller)
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/forker.py", line 206, in init_sage
        controller.load_environment()
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/control.py", line 521, in load_environment
        return import_module(self.options.environment)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/repl/ipython_kernel/all_jupyter.py", line 7, in <module>
        from .widgets_sagenb import (input_box, text_control, slider,
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/repl/ipython_kernel/widgets_sagenb.py", line 30, in <module>
        from ipywidgets.widgets import (IntSlider, IntRangeSlider, FloatSlider,
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/ipywidgets/__init__.py", line 25, in <module>
        from .widgets import *
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
        from .widget import Widget, CallbackDispatcher, register, widget_serialization
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/ipywidgets/widgets/widget.py", line 18, in <module>
        from ipykernel.comm import Comm
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/ipykernel/__init__.py", line 2, in <module>
        from .connect import *
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/ipykernel/connect.py", line 18, in <module>
        import jupyter_client
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/jupyter_client/__init__.py", line 4, in <module>
        from .connect import *
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/jupyter_client/connect.py", line 21, in <module>
        import zmq
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/__init__.py", line 50, in <module>
        from zmq import backend
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/__init__.py", line 40, in <module>
        reraise(*exc_info)
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
        raise value
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/__init__.py", line 27, in <module>
        _ns = select_backend(first)
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/select.py", line 28, in select_backend
        mod = __import__(name, fromlist=public_api)
      File "/local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
        from . import (constants, error, message, context,
    ImportError: /local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/cython/_poll.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
**********************************************************************
File "src/sage/doctest/test.py", line 525, in sage.doctest.test
Failed example:
    ok or out
Expected:
    True
Got:
    b'Running doctests with ID 2020-09-08-21-18-39-74bd0f78.\nGit branch: develop\nUsing --optional=build,dochtml,memlimit,sage\nDoctesting 1 file.\n'
**********************************************************************
```
Since the failure is also on gentoo, I suspect something on gentoo as being the cause. Do you see this?

**Comment by strogdon** [comment]
I should not that 
```
local/sage-git/sage/local/lib/python3.8/site-packages/zmq/backend/cython/_poll.cpython-38-x86_64-linux-gnu.so
``` 
has a ton of undefined symbols in it as well as the corresponding file on gentoo. These may be resolved at runtime.

**Comment by kiwifb** [comment]
Unresolved symbols are not always an issue, especially like in this case, they are probably libpython symbols that will automatically be loaded with the interpreter.
I haven't run the testsuite with 3.8 this time around. I was impressed how I had the same results with both 3.7 and 3.8 the first time Volker tried to merge it. Will run the testsuite with python3.8 shortly.

**Comment by kiwifb** [comment]
```
fbissey@moonloop ~ $ EPYTHON=python3.8 sage -t --long --warn-long 102.0 --random-seed=0 --memlimit=0 /usr/lib/python3.8/site-packages/sage/doctest/test.py 
Running doctests with ID 2020-09-09-20-33-13-3a213fa2.
Using --optional=dochtml,optional,sage
Doctesting 1 file.
sage -t --long --warn-long 102.0 --random-seed=0 /usr/lib/python3.8/site-packages/sage/doctest/test.py
    [57 tests, 137.90 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 137.9 seconds
    cpu time: 0.2 seconds
    cumulative wall time: 137.9 seconds
fbissey@moonloop ~ $ sage -t --long --warn-long 102.0 --random-seed=0 --memlimit=0 /usr/lib/python3.7/site-packages/sage/doctest/test.py 
Running doctests with ID 2020-09-09-20-38-43-d0e34a16.
Using --optional=dochtml,optional,sage
Doctesting 1 file.
sage -t --long --warn-long 102.0 --random-seed=0 /usr/lib/python3.7/site-packages/sage/doctest/test.py
    [57 tests, 139.76 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 139.8 seconds
    cpu time: 0.2 seconds
    cumulative wall time: 139.8 seconds
```
I don't have a "recent" vanilla build. The last one I have is from testing the merge of sage-brial.

**Comment by strogdon** [comment]
It's the crazy `memlimit` option again. The doctest (line 522) has
```
P = subprocess.Popen(["sage", "-t", "--warn-long", "0", "--random-seed=0", "--memlimit=2000", "memlimit.rst"], stdout=subprocess.PIPE, **kwds)
```
If I change the `memlimit` to `--memlimit=2100` then the doctest passes. Passing `--memlimit=0` on the command line apparently does nothing here. I guess there is no way to override the option once hardcoded. This is all very strange since I have plenty of memory during the doctest. I don't know what memory, perhaps hidden, is being comsumed.

**Comment by kiwifb** [comment]
Not that one at any rate. This is still really strange that the failures seems to be mostly on your system and nowhere else. I am sometimes wondering about it.

**Comment by strogdon** [comment]
I wonder too. The only saving thing is that, in most cases, there is a work-a-round. The memory issues started with py3, first in prefix, then on my laptop using gentoo and now with vanilla on the same laptop. I had always thought it was python-related since that was the only thing that really changed - most notably in prefix, where nothing on the host has changed.

**Comment by strogdon** [comment]
Example of the failure on Gentoo from sage:
```
sage: import subprocess                                                         
sage: P = subprocess.Popen(["sage", "-t", "--warn-long", "0", "--random-seed=0",
....: "--memlimit=2060", "memlimit.rst"], stdout=subprocess.PIPE)
sage: Process DocTestWorker-1:                                                  
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/forker.py", line 2191, in run
    task(self.options, self.outtmpfile, msgpipe, self.result_queue)
  File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/doctest/forker.py", line 2541, in __call__
    result_queue.put(result, False)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 88, in put
    self._start_thread()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread
    self._thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
sage:                                                                           
sage: P = subprocess.Popen(["sage", "-t", "--warn-long", "0", "--random-seed=0",
....: "--memlimit=2070", "memlimit.rst"], stdout=subprocess.PIPE)
sage:
```
Nothing has been really run and no memory is used, but changing `memlimit` from 2060 to 2070 gives no failure.

And now from the shell prompt
```
$ sage -t --warn-long 0 --random-seed=0 --memlimit=2060 memlimit.rst
Running doctests with ID 2020-09-10-10-26-48-b41fb205.
Using --optional=dochtml,memlimit,optional,sage
Doctesting 1 file.
Process DocTestWorker-1:
sage -t --warn-long 0.0 --random-seed=0 memlimit.rst
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 2191, in run
    task(self.options, self.outtmpfile, msgpipe, self.result_queue)
  File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 2541, in __call__
    result_queue.put(result, False)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 88, in put
    self._start_thread()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 173, in _start_thread
    self._thread.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
    Bad exit: 1
**********************************************************************
Tests run before process (pid=15989) failed:

**********************************************************************
----------------------------------------------------------------------
sage -t --warn-long 0.0 --random-seed=0 memlimit.rst  # Bad exit: 1
----------------------------------------------------------------------
```
and with `memlimit=2070`
```
$ sage -t --warn-long 0 --random-seed=0 --memlimit=2070 memlimit.rstRunning doctests with ID 2020-09-10-10-28-05-e73e85a1.
Using --optional=dochtml,memlimit,optional,sage
Doctesting 1 file.
sage -t --warn-long 0.0 --random-seed=0 memlimit.rst
    FileNotFoundError in doctesting framework
**********************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 2520, in __call__
    doctests, extras = self._run(runner, options, results)
  File "/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 2563, in _run
    doctests, extras = self.source.create_doctests(sage_namespace)
  File "/usr/lib/python3.8/site-packages/sage/doctest/sources.py", line 726, in create_doctests
    raise IOError(errno.ENOENT, "File does not exist", self.path)
FileNotFoundError: [Errno 2] File does not exist: 'memlimit.rst'

----------------------------------------------------------------------
sage -t --warn-long 0.0 --random-seed=0 memlimit.rst  # FileNotFoundError in doctesting framework
----------------------------------------------------------------------
```
The file `memlimit.rst` does not exist so the failure.

Similar failures in Prefix and with Vanilla. Vanilla uses the same python as Gentoo, but Prefix is on another machine.

**Comment by kiwifb** [comment]
This and #610 are probably different aspect of the same issue.

**Comment by kiwifb** [comment]
I am going to assume we can close this.
