### ISSUE TITLE
Undefined _bitset_* symbols with gcc9 building vanilla sage 9.2.beta14

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#602]
Now this may be a vanilla issue but I thought I would go here first. It's an incremental upgrade from beta13 -> beta14. The failure:
```
[dochtml] Traceback (most recent call last):
[dochtml]   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
[dochtml]     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
[dochtml]   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
[dochtml]     return _get_module_details(pkg_main_name, error)
[dochtml]   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
[dochtml]     __import__(pkg_name)
[dochtml]   File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage_setup/docbuild/__init__.py", line 58, in <module>
[dochtml]     import sage.all
[dochtml]   File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/all.py", line 129, in <module>
[dochtml]     from sage.data_structures.all import *
[dochtml]   File "/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/all.py", line 3, in <module>
[dochtml]     from .bitset import Bitset, FrozenBitset
[dochtml] ImportError: /local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so: undefined symbol: _bitset_intersection
make[3]: *** [Makefile:1877: doc-html] Error 1
make[2]: *** [Makefile:1767: all-start] Error 2
``` 
and
```
$ ldd -r /local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so | grep _bit
undefined symbol: _bitset_intersection  (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_first_in_limb_nonzero (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_first_in_limb (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_issubset      (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_difference    (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_isempty       (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_eq    (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_symmetric_difference  (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_len   (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
undefined symbol: _bitset_union (/local/sage-git/sage/local/lib/python3.8/site-packages/sage/data_structures/bitset.cpython-38-x86_64-linux-gnu.so)
```
Perhaps something should be rebuilt, but what?

**Comment by kiwifb** [comment]
This is vanilla? I was quite shocked that it built on all of Volker's bots without the stuff from https://trac.sagemath.org/ticket/30675.

**Comment by strogdon** [comment]
Should I report on [trac #30675](https://trac.sagemath.org/ticket/30675)? It appears that gcc9 is a  problem too.

**Comment by strogdon** [comment]
I will report on trac. The indication is that https://trac.sagemath.org/ticket/30675 fixes things.

**Comment by kiwifb** [comment]
Sorry was offline for a while, thanks for the comments on the ticket.
