### ISSUE TITLE
html-docs fail - new Prefix install

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#612]
This is for a new Prefix install from "scratch".
```
[categorie] The inventory files are in ../../build_doc/inventory/en/reference/categories.
Error building the documentation.
Traceback (most recent call last):
  File "sage_setup/docbuild/__main__.py", line 2, in <module>
    main()
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/__init__.py", line 1730, in main
    builder()
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/__init__.py", line 343, in _wrapper
    getattr(get_builder(document), 'inventory')(*args, **kwds)
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/__init__.py", line 569, in _wrapper
    self._build_everything_except_bibliography(lang, format, *args, **kwds)
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/__init__.py", line 555, in _build_everything_except_bibliography
    build_many(build_ref_doc, non_references)
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/__init__.py", line 295, in build_many
    _build_many(target, args, processes=NUM_THREADS)
  File "/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/sage_setup/docbuild/utils.py", line 289, in build_many
    raise worker_exc.original_exception
OSError: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/build/lib/sage/categories/finite_coxeter_groups.py:docstring of sage.categories.finite_coxeter_groups.FiniteCoxeterGroups.ParentMethods.permutahedron:50: WARNING: Exception occurred in plotting finite_coxeter_groups-1
 ^[[31;01m*^[[0m ERROR: sci-mathematics/sage-9999::sage-on-gentoo failed (compile phase):
 ^[[31;01m*^[[0m   failed to produce html doc
```
The problem is apparently with `gapdoc`:
```
[graphs   ] updating environment: [new config] 73 added, 0 changed, 0 removed
#I  gapdoc package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  GAP: needed package gapdoc cannot be loaded
Error, failed to load needed package `gapdoc' (version >= 1.2)
Syntax warning: Unbound global variable in /storage/strogdon/gentoo-rap/usr/sh\
are/gap/lib/init.g:803
    ColorPrompt( UserPreference( "UseColorPrompt" ) );
               ^
Error, SetGasmanMessageStatus: function is not yet defined
```
If I `emerge sage`,  `gapdoc` is not pulled in. However if I `emerge -puD sage` I get
```

Calculating dependencies... done!
[ebuild  NS    ] dev-lang/python-3.10.0_alpha1 [3.6.12, 3.7.9, 3.8.6, 3.9.0] USE="sqlite*" 
[ebuild  N     ] dev-gap/GAPDoc-1.6.2-r2 
[ebuild  N     ] dev-gap/laguna-3.9.3 
[ebuild  N     ] dev-gap/factint-1.6.3 
[ebuild  N     ] dev-gap/ctbllib-1.2_p2-r5 
[ebuild  N     ] dev-gap/polycyclic-2.15.1 
[ebuild  N     ] dev-gap/Alnuth-3.1.2 
[ebuild  N     ] dev-gap/radiroot-2.8-r2 
[ebuild  N     ] dev-gap/polenta-1.3.9 
[ebuild  N     ] dev-gap/atlasrep-2.1_p0-r1 
[ebuild  N     ] dev-gap/tomlib-1.2.9 
[ebuild  N     ] dev-gap/AutoDoc-2019.09.04 
[ebuild  N     ] dev-gap/utils-0.69 
[ebuild  N     ] dev-gap/resclasses-4.7.2 
[ebuild  N    #] sci-mathematics/sage-9999  USE="debug doc-html doc-pdf jmol latex testsuite -X -bliss" L10N="en fr -ca -de -es -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python3_7 python3_8"
```
So now `gapdoc` is pulled in with a bunch of others. I'm not sure if a dependency is missing - if all these packages are needed - or if it's just because of Prefix. In any event `gapdoc` is needed to build the html-docs. Not sure about the others nor why `gapdoc` was not pulled in.

**Comment by kiwifb** [comment]
All right. Minimum and recommended gap packages are in `PDEPEND` so they can be installed after gap itself (which we want). But obviously we'd like them installed before sage and not after, which is what must have happened to you.

Simplest solution is probably to add some dependencies to sage. Another solution is to revive gap-core which was for a short time in the science overlay and have gap as a meta package which would pull the other stuff. And that would mean no change to the current sage dependencies but a lot of brutal tree moves.

**Comment by strogdon** [comment]
I now see, after installing `gapdoc`, that all the others are needed. There are complaints in building the docs. It's your choice, but I now know what to do. Most users would probably not see this.

**Comment by strogdon** [comment]
FWIW, after installing just `gapdoc` both the html-docs and pdf-docs build. However, I do see the following warnings
```
#I  alnuth package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  ctbllib package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  factint package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  laguna package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  polenta package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  polycyclic package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  resclasses package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  tomlib package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  alnuth package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  ctbllib package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  factint package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  laguna package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  polenta package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  polycyclic package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  resclasses package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
#I  tomlib package is not available. Check that the name is correct
#I  and it is present in one of the GAP root directories (see '??RootPaths')
```

**Comment by kiwifb** [comment]
That's interesting to know actually. Those would be message from gap when trying to load the packages and they are not there. It is both from the minimum set and the recommended set.

**Comment by strogdon** [comment]
Perhaps off topic. On the new prefix I have 4 doctest failures. I can reslove all except
```
sage -t --long --random-seed=0 usr/lib/python3.8/site-packages/sage/cpython/dict_del_by_value.pyx
**********************************************************************
File "usr/lib/python3.8/site-packages/sage/cpython/dict_del_by_value.pyx", line 268, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value
Failed example:
    test_del_dictitem_by_exact_value(D, ZZ, 2)
Exception raised:
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 720, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/storage/strogdon/gentoo-rap/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value[7]>", line 1, in <module>
        test_del_dictitem_by_exact_value(D, ZZ, Integer(2))
      File "sage/cpython/dict_del_by_value.pyx", line 275, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/build/cythonized/sage/cpython/dict_del_by_value.c:2427)
        del_dictitem_by_exact_value(<PyDictObject *>D, <PyObject *>value, h)
    TypeError: an integer is required
**********************************************************************
File "usr/lib/python3.8/site-packages/sage/cpython/dict_del_by_value.pyx", line 271, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value
Failed example:
    test_del_dictitem_by_exact_value(D, QQ, 1)
Exception raised:
    Traceback (most recent call last):
      File "/storage/strogdon/gentoo-rap/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 720, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/storage/strogdon/gentoo-rap/usr/lib/python3.8/site-packages/sage/doctest/forker.py", line 1145, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value[9]>", line 1, in <module>
        test_del_dictitem_by_exact_value(D, QQ, Integer(1))
      File "sage/cpython/dict_del_by_value.pyx", line 275, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value (/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_8/build/cythonized/sage/cpython/dict_del_by_value.c:2427)
        del_dictitem_by_exact_value(<PyDictObject *>D, <PyObject *>value, h)
    TypeError: an integer is required
**********************************************************************
```

**Comment by kiwifb** [comment]
Yes, this is because sage carries a cython patch. The patch in question is not included in the current 0.29 branch as far as I know, but the next major release of cython (cython-3 I remember hearing). At first I thought it would be quick after the disappearance of py2.7 for it to be released. But we are still waiting after several months.

**Comment by kiwifb** [comment]
I think I will go for a gap ebuild which is a meta ebuild. The idea will be that it needs to have all its dependencies installed before being installed. This is what you will need to have a functional gap as a dependency. The current gap will become gap-core which will coincide with sources distributed on github that don't have any extra packages.

The only annoying bit is that I really want to do that for gap-4.11.0 but not earlier if I can help it.

**Comment by kiwifb** [comment]
Gap upgrade is on again. And now that I am experimenting with the content of my gap branch I see that I wasn't as careful as I thought. It will be bumpy again :(

**Comment by kiwifb** [comment]
I hope this gap upgrade will be a bit more explicit in what is needed to do. I have put blockers in place for when it lands in the main branch. I had to revert to the full gap tarball. The gap-core one doesn't come with pre-built html doc. No html doc means no basic documentation from gap or sage and doctest failures. To build the doc the minimum set of packages need to be in the source tree of gap. I may consider it for 4.12.0.

**Comment by kiwifb** [comment]
9.3.beta4 has just hit github and sage-on-gentoo master branch has been updated. Let's see if it behaves nice for you.

**Comment by strogdon** [comment]
OK, this is what I see before I start removing packages.
```
$ emerge -pv =sci-mathematics/sage-9999

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] net-dns/c-ares-1.17.1:0/2::gentoo  USE="-static-libs" 1,484 KiB
[ebuild  N     ] net-libs/nodejs-15.3.0:0/15::gentoo  USE="icu npm snapshot ssl system-ssl -debug -doc -inspector -pax_kernel -system-icu -systemtap -test" CPU_FLAGS_X86="sse2" 32,421 KiB
[ebuild     U  ] dev-python/sympy-1.7::gentoo [1.6.2::gentoo] USE="-examples -imaging -ipython -latex -mathml -opengl -pdf -png -pyglet -symengine -test (-texmacs) -theano" PYTHON_TARGETS="python3_7 python3_8 -python3_9" 6,807 KiB
[ebuild  N     ] sci-mathematics/gap-core-4.11.0::sage-on-gentoo  USE="readline recommended_pkgs -debug -emacs -memcheck -valgrind -vim-syntax" 395,996 KiB
[ebuild     U  ] dev-gap/GAPDoc-1.6.3::sage-on-gentoo [1.6.2-r2::sage-on-gentoo] 243 KiB
[ebuild     U  ] dev-gap/SmallGrp-1.4.1::sage-on-gentoo [1.3-r2::sage-on-gentoo] 18,286 KiB
[ebuild     U  ] dev-gap/transgrp-3.0:0/0::sage-on-gentoo [2.0.4-r2:0/4.10.2::sage-on-gentoo] 59,699 KiB
[ebuild     U  ] dev-gap/primgrp-3.4.0::sage-on-gentoo [3.3.2-r2::sage-on-gentoo] 14,100 KiB
[ebuild  N     ] dev-python/jupyter_jsmol-0.2.4::sage-on-gentoo  USE="-test" PYTHON_TARGETS="python3_7 python3_8 -python3_9" 6,162 KiB
[ebuild     U  ] sci-mathematics/gap-4.11.0-r3:0/0::sage-on-gentoo [4.10.2-r1:0/4.10.2::sage-on-gentoo] USE="readline recommended_pkgs -debug% -emacs -memcheck% -valgrind% -vim-syntax" 0 KiB
[ebuild   R   #] sci-mathematics/sage-9999::sage-on-gentoo  USE="debug doc-html doc-pdf jmol latex testsuite -X -bliss" L10N="en fr -ca -de -es -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python3_7 python3_8" 0 KiB
[blocks B      ] <sci-mathematics/gap-4.11.0 ("<sci-mathematics/gap-4.11.0" is blocking sci-mathematics/gap-core-4.11.0)
[blocks B      ] <=dev-gap/transgrp-2.0.4-r2 ("<=dev-gap/transgrp-2.0.4-r2" is hard blocking sci-mathematics/gap-core-4.11.0)

Total: 11 packages (6 upgrades, 4 new, 1 reinstall), Size of downloads: 535,194 KiB
Conflict: 2 blocks (2 unsatisfied)
```
On upgrade I usually do `emerge -C sage && emerge -1 sage`.  Taking this route I see
```
$ emerge -1p sci-mathematics/sage

These are the packages that would be merged, in order:

Calculating dependencies \

!!! Problem resolving dependencies for sci-mathematics/sage
... done!

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

sci-mathematics/gap:0

  (sci-mathematics/gap-4.11.0-r3:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="(prefix) readline recommended_pkgs -debug -emacs -memcheck -valgrind -vim-syntax" conflicts with
    >=sci-mathematics/gap-4.10.1:0/4.10.2= required by (dev-gap/io-4.7.0:0/0::sage-on-gentoo, installed) USE="(prefix)"
                                ^^^^^^^^^^
    sci-mathematics/gap:0/4.10.2 required by (dev-gap/transgrp-2.0.4-r2:0/4.10.2::sage-on-gentoo, installed) USE="(prefix)"
                       ^^^^^^^^^


!!! The following update(s) have been skipped due to unsatisfied dependencies
!!! triggered by backtracking:

sci-mathematics/sage:0

!!! The ebuild selected to satisfy "sci-mathematics/sage" has unmet requirements.
- sci-mathematics/sage-9.2-r1::sage-on-gentoo USE="debug doc-html doc-html-bin doc-pdf jmol latex (prefix) testsuite -X -bliss -doc-pdf-bin" L10N="en fr -ca -de -es -hu -it -ja -pt -ru -tr" PYTHON_TARGETS="python3_7 python3_8"

  The following REQUIRED_USE flag constraints are unsatisfied:
    doc-html-bin? ( !doc-html !doc-pdf )

  The above constraints are a subset of the following complete expression:
    doc-html? ( jmol l10n_en ) doc-pdf? ( jmol l10n_en ) testsuite? ( any-of ( doc-html doc-html-bin ) ) doc-html-bin? ( !doc-html !doc-pdf l10n_en ) doc-pdf-bin? ( !doc-html !doc-pdf l10n_en ) any-of ( python_targets_python3_7 python_targets_python3_8 )
```
In the first case it appears that `sci-mathematics/gap-4.10.2-r1` and  `dev-gap/transgrp-2.0.4-r2` must be removed. In the latter case perhaps only `dev-gap/transgrp-2.0.4-r2` has to be removed? The `>=sci-mathematics/gap-4.10.1:0/4.10.2=` for `dev-gapio-4.7.0` is what was required prior to https://github.com/cschwan/sage-on-gentoo/commit/b2cd2a7ccc8de0e6f23405a08745427557748cc

**Comment by kiwifb** [comment]
Only transgrp has to be removed, it is a hard block. gap itself is soft block so gap-core can take ownership of the files to install. For transgrp the issue is getting rid of the "slotting".

**Comment by strogdon** [comment]
On gentoo I believe `>=net-libs/nodejs-15.2.0[npm]` and `dev-python/jupyter_jsmol-0.2.4` will have to be keyworded.

**Comment by kiwifb** [comment]
I forgot about nodejs, in the end it is not needed as you cannot use from portage. Works fine when I call ebuild as a simple user but when run with emerge the network sandbox gets in the way.

**Comment by kiwifb** [comment]
Dependency removed in overlay. jupyter_jsmol is keyworded already.

**Comment by strogdon** [comment]
After removing `transgrp` I have
```
$ emerge -1p sci-mathematics/sage

These are the packages that would be merged, in order:

Calculating dependencies \

!!! Problem resolving dependencies for sci-mathematics/sage
... done!

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

sci-mathematics/gap:0

  (sci-mathematics/gap-4.11.0-r3:0/0::sage-on-gentoo, ebuild scheduled for merge) USE="(prefix) readline recommended_pkgs -debug -emacs -memcheck -valgrind -vim-syntax" conflicts with
    >=sci-mathematics/gap-4.10.1:0/4.10.2= required by (dev-gap/io-4.7.0:0/0::sage-on-gentoo, installed) USE="(prefix)"
```
So I may have to remove io or is it gap? The io commit was kind of a silent bump wasn't  it? On gentoo I have `io-4.6.0` installed.

**Comment by kiwifb** [comment]
May have been. It looks like I need to add it to my list of blockers. It
will be later as I am getting busy with other stuff.

**Comment by strogdon** [comment]
For future reference after removing `transgrp` and `io` things look good
```
$ emerge -1p sage

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] dev-python/sympy-1.7 [1.6.2]
[ebuild  N     ] dev-python/jupyter_jsmol-0.2.4  USE="-test" PYTHON_TARGETS="python3_7 python3_8 -python3_9" 
[ebuild  N     ] sci-mathematics/gap-core-4.11.0  USE="readline recommended_pkgs -debug -emacs -memcheck -valgrind -vim-syntax" 
[ebuild  N     ] dev-gap/transgrp-3.0 
[ebuild     U  ] dev-gap/GAPDoc-1.6.3 [1.6.2-r2]
[ebuild     U  ] dev-gap/primgrp-3.4.0 [3.3.2-r2]
[ebuild     U  ] dev-gap/SmallGrp-1.4.1 [1.3-r2]
[ebuild     U  ] sci-mathematics/gap-4.11.0-r3 [4.10.2-r1] USE="-debug% -memcheck% -valgrind%" 
[blocks b      ] <sci-mathematics/gap-4.11.0 ("<sci-mathematics/gap-4.11.0" is blocking sci-mathematics/gap-core-4.11.0)
[ebuild   R   #] sci-mathematics/sage-9999
```

**Comment by kiwifb** [comment]
Nothing much more that I can do about `io`, it like a number of other packages linking to libgap had a dependency to `gap:=` looking out for subslot to trigger rebuild. It is one of those cases where it doesn't work anyway.

**Comment by strogdon** [comment]
I thought everything was OK but maybe no. Notice above that after removing `io-4.7.0` and emerging `sage` that `io` is not pulled in. This was on prefix. There was no issue on gentoo where before the upgrade `io-4.6.0` was installed. It appears that `atlasrep` pulls in `io`. The upgrade on gentoo pulled in the latest `atlasrep` along with `io-4.7.0`. But on prefix `atlasrep` was not upgraded. Prefix is `stuck` at `atlasrep-2.1_p0-r1` which is no longer available. Oddly, on prefix there is no emerge command that will pull in `io`, aside from `emerge -1 atlasrep`.

**Comment by strogdon** [comment]
If I mask `dev-python/fpylll-0.5.3` then `emerge -puD sage` will update outdated `gap` packagaes and pull in `io-4.7.0`

**Comment by kiwifb** [comment]
Ok, that's just plain weird. Although it sometimes happen that because of one thing you get a report of other things potentially blocking the merge when they don't.

**Comment by kiwifb** [comment]
Can we close this now?

**Comment by strogdon** [comment]
Yes. I'll close.
