### ISSUE TITLE
TypeError: an integer is required - sage/cpython/dict_del_by_value.pyx (cython patch)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#644]
I have this failure that's not present with vanilla. Have I seen this before?
```
sage -t --long --warn-long 94.8 --random-seed=0 /usr/lib/python3.9/site-packages/sage/cpython/dict_del_by_value.pyx
**********************************************************************
File "/usr/lib/python3.9/site-packages/sage/cpython/dict_del_by_value.pyx", line 268, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value
Failed example:
    test_del_dictitem_by_exact_value(D, ZZ, 2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.9/site-packages/sage/doctest/forker.py", line 1133, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value[7]>", line 1, in <module>
        test_del_dictitem_by_exact_value(D, ZZ, Integer(2))
      File "sage/cpython/dict_del_by_value.pyx", line 275, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value (/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_9/build/cythonized/sage/cpython/dict_del_by_value.c:2434)
        del_dictitem_by_exact_value(<PyDictObject *>D, <PyObject *>value, h)
    TypeError: an integer is required
**********************************************************************
File "/usr/lib/python3.9/site-packages/sage/cpython/dict_del_by_value.pyx", line 271, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value
Failed example:
    test_del_dictitem_by_exact_value(D, QQ, 1)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/sage/doctest/forker.py", line 714, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.9/site-packages/sage/doctest/forker.py", line 1133, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value[9]>", line 1, in <module>
        test_del_dictitem_by_exact_value(D, QQ, Integer(1))
      File "sage/cpython/dict_del_by_value.pyx", line 275, in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value (/var/tmp/portage/sci-mathematics/sage-9999/work/sage-9999/src-python3_9/build/cythonized/sage/cpython/dict_del_by_value.c:2434)
        del_dictitem_by_exact_value(<PyDictObject *>D, <PyObject *>value, h)
    TypeError: an integer is required
**********************************************************************
1 item had failures:
   2 of  12 in sage.cpython.dict_del_by_value.test_del_dictitem_by_exact_value
    [22 tests, 2 failures, 2.68 s]
----------------------------------------------------------------------
sage -t --long --warn-long 94.8 --random-seed=0 /usr/lib/python3.9/site-packages/sage/cpython/dict_del_by_value.pyx  # 2 doctests failed
```
Is it due to a cython patch, I can't remember.

**Comment by kiwifb** [comment]
It is due to cython patch included in sage yes. It's been around for a while, we are still waiting for that elusive new major cython release.

**Comment by kiwifb** [comment]
This can officially be closed as upstream moved on :)
