### ISSUE TITLE
sandbox violation building sage-doc-9999

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#667]
This seems to have occurred after adding all available `L10N` to `make.conf`.
```
/usr/bin/python3.9 -m sage_docbuild --no-pdf-links reference/references inventory 
 * ACCESS DENIED:  mkostemp:     /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
 * ACCESS DENIED:  mkostemp:     /usr/share/texmf-dist/fonts/opentype/public/haranoaji-extra/.uuid.TMP-XXXXXX
 * ACCESS DENIED:  mkostemp:     /usr/share/texmf-dist/fonts/truetype/public/ipaex/.uuid.TMP-XXXXXX
 ```
And from `sandbox.log`
```
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: mkostemp
S: deny
P: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
A: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
R: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
C: fc-list --format=%{file}\n

F: mkostemp
S: deny
P: /usr/share/texmf-dist/fonts/opentype/public/haranoaji-extra/.uuid.TMP-XXXXXX
A: /usr/share/texmf-dist/fonts/opentype/public/haranoaji-extra/.uuid.TMP-XXXXXX
R: /usr/share/texmf-dist/fonts/opentype/public/haranoaji-extra/.uuid.TMP-XXXXXX
C: fc-list --format=%{file}\n

F: mkostemp
S: deny
P: /usr/share/texmf-dist/fonts/truetype/public/ipaex/.uuid.TMP-XXXXXX
A: /usr/share/texmf-dist/fonts/truetype/public/ipaex/.uuid.TMP-XXXXXX
R: /usr/share/texmf-dist/fonts/truetype/public/ipaex/.uuid.TMP-XXXXXX
C: fc-list --format=%{file}\n

F: mkostemp
S: deny
P: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
A: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
R: /usr/share/texmf-dist/fonts/opentype/public/haranoaji/.uuid.TMP-XXXXXX
C: /opt/openjdk-bin-8.312_p07/bin/java -Xmx512m -Duser.home=/var/tmp/portage/sci-mathematics/sage-doc-9999/homedir/.sage -Djava.awt.headless=true -jar /usr/share/sage-jmol-bin/lib/JmolData.jar -iox -g 500x500 -J set defaultdirectory "/var/tmp/portage/sci-mathematics/sage-doc-9999/homedir/.sage/temp/localhost/64/dir_a0pqklne/scene.spt.zip"
script SCRIPT
 -j write PNG '/var/tmp/portage/sci-mathematics/sage-doc-9999/homedir/.sage/temp/localhost/64/dir_a0pqklne/preview.png'
```

**Comment by strogdon** [comment]
Perhaps things are out of sync. This looks weird, sage-doc-9999 fails to build?

**Comment by strogdon** [comment]
The failure
```
kpathsea: Running mktextfm lass1200
[reference]     probability: 0 todos, 3 index, 1657 citations, 2 modules
[reference]     quadratic_forms: 6 todos, 14 index, 1657 citations, 13 modules
[reference]     quasimodfrm: 0 todos, 3 index, 1657 citations, 2 modules
[reference]     quat_algebras: 0 todos, 3 index, 1657 citations, 2 modules
[reference]     quivers: 2 todos, 8 index, 1657 citations, 7 modules
[reference] Extension error (sage_docbuild.ext.multidocs):
[reference] Handler <function merge_environment at 0x7f0f685e1d30> for event 'env-updated' threw an exception (exception: 'utf-8' codec can't decode byte 0x95 in position 78: invalid start byte)
LaTeX file written to /var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference
Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 656, in pdf
    super().pdf()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 254, in pdf
    with open(tex_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/reference.tex'

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean" first and try again.
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input lass1200
This is METAFONT, Version 2.71828182 (TeX Live 2021 Gentoo Linux) (preloaded base=mf)
```
```
/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/reference.tex
``` 
does not exit but 
```
/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/references/references.tex
``` 
does exist.

**Comment by kiwifb** [comment]
We are talking about pdf doc I presume. That's reminiscent of what Volker is seeing with some paths not being relatives to the right level. I will have a go at pdf, but the first message suggests that some texlive dependencies may be missing.

**Comment by kiwifb** [comment]
It also looks like I hadn't properly synchronised branches when I removed the combined html and pdf doc building. I suspect your later error may be that.

**Comment by kiwifb** [comment]
Had to deal with the fact that the sympy dependency needed upgrading after 1.8 left the tree. It was in the way of preparing for python 3.10. Will take a bit before I go back to pdf doc.

**Comment by strogdon** [comment]
I'm thinking syncing may be the problem. The pdf-docs build on vanilla, so I think dependencies are OK. Shouldn't  the temp folders be created under the build folder and not on the live system? For reference I have `L10N="ca de en es fr hu it ja pt ru tr"`.

**Comment by kiwifb** [comment]
The temp folders should be dealt with by https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage-doc/sage-doc-9999.ebuild#L79 and https://github.com/cschwan/sage-on-gentoo/blob/master/sci-mathematics/sage/files/sage-9.3-forcejavatmp.patch font related files shouldn't spill over.

**Comment by kiwifb** [comment]
So, on the volker branch of the overlay. Build html+pdf for en and fr, no issue. Putting all possible language
```
(/usr/share/texmf-dist/tex/latex/txfonts/ts1txtt.fd) [3] [983] [4] [984^[[91m[combinat ]^[[39;49;00m ^[[91mException occurred:^[[39;49;00m
]^[[91m[combinat ]^[[39;49;00m   File "/usr/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 520, in get_doctree
^[[91m[combinat ]^[[39;49;00m     doctree = pickle.load(f)
^[[91m[combinat ]^[[39;49;00m EOFError: Ran out of input
^[[91m[combinat ]^[[39;49;00m ^[[91mThe full traceback has been saved in /dev/shm/portage/sci-mathematics/sage-doc-9999/temp/sphinx-err-qcn6ri0t.log, if you want to report the issue to the devel>
^[[91m[combinat ]^[[39;49;00m Please also report this if it was a user error, so that a better error message can be provided next time.
^[[91m[combinat ]^[[39;49;00m A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 823, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 137, in f
    runsphinx()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/sphinxbuild.py", line 323, in runsphinx
    sys.stderr.raise_errors()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/sphinxbuild.py", line 258, in raise_errors
    raise OSError(self._error)
OSError: ^[[91mException occurred:^[[39;49;00m

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean" first and try again.
```
and 
```
$ cat /dev/shm/portage/sci-mathematics/sage-doc-9999/temp/sphinx-err-qcn6ri0t.log
# Sphinx version: 4.3.1
# Python version: 3.9.9 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   preparing documents...
#   done
#   writing output... [  0%] index
#   writing output... [  0%] module_list
#   writing output... [  0%] sage/combinat/abstract_tree
#   writing output... [  1%] sage/combinat/affine_permutation
#   writing output... [  1%] sage/combinat/algebraic_combinatorics
#   writing output... [  1%] sage/combinat/all
#   writing output... [  1%] sage/combinat/alternating_sign_matrix
#   writing output... [  2%] sage/combinat/backtrack
# Loaded extensions:
#   sphinx.ext.mathjax (4.3.1) from /usr/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.9/site-packages/alabaster/__init__.py
#   sage_docbuild.ext.inventory_builder (unknown version) from /usr/lib/python3.9/site-packages/sage_docbuild/ext/inventory_builder.py
#   sage_docbuild.ext.multidocs (unknown version) from /usr/lib/python3.9/site-packages/sage_docbuild/ext/multidocs.py
#   sage_docbuild.ext.sage_autodoc (4.3.1) from /usr/lib/python3.9/site-packages/sage_docbuild/ext/sage_autodoc.py
#   sphinx.ext.todo (4.3.1) from /usr/lib/python3.9/site-packages/sphinx/ext/todo.py
#   sphinx.ext.extlinks (4.3.1) from /usr/lib/python3.9/site-packages/sphinx/ext/extlinks.py
#   IPython.sphinxext.ipython_directive (unknown version) from /usr/lib/python3.9/site-packages/IPython/sphinxext/ipython_directive.py
#   matplotlib.sphinxext.plot_directive (3.4.3) from /usr/lib/python3.9/site-packages/matplotlib/sphinxext/plot_directive.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 344, in build
    self.builder.build_update()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 532, in write
    self._write_serial(sorted(docnames))
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 539, in _write_serial
    doctree = self.env.get_and_resolve_doctree(docname, self)
  File "/usr/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 532, in get_and_resolve_doctree
    doctree = self.get_doctree(docname)
  File "/usr/lib/python3.9/site-packages/sphinx/environment/__init__.py", line 520, in get_doctree
    doctree = pickle.load(f)
EOFError: Ran out of input
```

**Comment by strogdon** [comment]
I'm on the `master` branch. Removed `ja` from `L10N` and `sage-doc-9999` builds and installs. Something is strange with how fonts are generated when `ja` included. The pdf Japanese docs do build on vanilla so this must be s-o-g related.

**Comment by strogdon** [comment]
Argh - gremlins? Added `ja` back into `L10N` and now `sage-doc-9999` builds and installs for ALL languages. No sandbox violation. I did this several times last evening with (obviously) different results. Perhaps something spooky is going on inside `sage_docbuild.ext.multidocs` (see https://github.com/cschwan/sage-on-gentoo/issues/667#issuecomment-1003882877).

**Comment by kiwifb** [comment]
Gremlins need to be found and thrown out in any case :) but this is awkward.

**Comment by strogdon** [comment]
Rebuilt vanilla docs (pdf+html) without a problem. Then tried `sage-doc-9999` again with
```
  [36)][74] (./SageTutorial.ind)[reference] Extension error (sage_docbuild.ext.multidocs):
[reference] Handler <function merge_environment at 0x7fd748dd7d30> for event 'env-updated' threw an exception (exception: 'utf-8' codec can't decode byte 0x95 in position 39: invalid start byte)
LaTeX file written to /var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference
)Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 656, in pdf
    super().pdf()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 254, in pdf
    with open(tex_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/reference.tex'
```
which is similar to https://github.com/cschwan/sage-on-gentoo/issues/667#issuecomment-1003882877.

Started the build again from where things left off with
```
>>> Compiling source in /var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999 ...
make -j9 doc-html doc-pdf PYTHON=/usr/bin/python3.9
make doc-inventory--reference-references
make[1]: Entering directory '/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc'
/usr/bin/python3.9 -m sage_docbuild --no-pdf-links reference/references inventory
Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 814, in _wrapper
    for module_name in self.get_new_and_updated_modules():
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 981, in get_new_and_updated_modules
    env = self.get_sphinx_environment()
  File "/usr/lib/python3.9/site-packages/sage_docbuild/__init__.py", line 878, in get_sphinx_environment
    env = pickle.load(f)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x95 in position 39: invalid start byte
```
No sandbox but something seems corrupted.

**Comment by kiwifb** [comment]
Coming back to this. I got some gremlins too. I discovered that the ebuild in my "production" overlay had been touched to suppress the parallel build of html+pdf in a single invocation. Reverting to full parallel build of html+pdf just worked. Very strange.

**Comment by strogdon** [comment]
I'm having trouble getting `sage-doc-9999` to build with `rc1`.
```
[reference] Extension error (sage_docbuild.ext.multidocs):
[reference] Handler <function merge_environment at 0x7fb27fab0ca0> for event 'env-updated' threw an exception (exception: 'utf-8' codec can't decode byte 0x94 in position 14: invalid start byte)
LaTeX file written to /var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference
Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 656, in pdf
    super().pdf()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 254, in pdf
    with open(tex_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/reference.tex'
```
which I've seen before. Once I have the `'utf-8' codec can't decode byte 0x94 in position 14: invalid start byte` I cannot restart the build. I have to start from the beginning.

**Comment by kiwifb** [comment]
`0x94`? I had `0x95` in an earlier failure that just disappeared. https://bytetool.web.app/en/ascii/code/0x94/ https://bytetool.web.app/en/ascii/code/0x95/ it makes me curious of the issue that Volker is sometimes having with pdf documentation.

**Comment by strogdon** [comment]
I have had the `0x95`. See https://github.com/cschwan/sage-on-gentoo/issues/667#issuecomment-1004356911

**Comment by strogdon** [comment]
In https://github.com/cschwan/sage-on-gentoo/issues/667#issuecomment-1011775510 I mentioned that I could not restart the build. However, If I remove the contents of
```
/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/doctrees/en/reference/references/
```
then I'm able to restart the build via `ebuild sage-doc-9999.ebuild install`.

**Comment by kiwifb** [comment]
Is it blocked during `compile` or `install` ebuild phase? I am not sure I should include a band aid for such a case as restarting a build. It definitely looks like some kind of random lock up in parallel builds.

**Comment by strogdon** [comment]
Only to fail again at the same point. But this time with
```
[reference] Extension error (sage_docbuild.ext.multidocs):
[reference] Handler <function merge_environment at 0x7fb248330ca0> for event 'env-updated' threw an exception (exception: 'str' object does not support item assignment)
LaTeX file written to /var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference
Error building the documentation.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 1775, in main
    builder()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 656, in pdf
    super().pdf()
  File "/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 254, in pdf
    with open(tex_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/tmp/portage/sci-mathematics/sage-doc-9999/work/build_doc/latex/en/reference/reference.tex'
```

**Comment by strogdon** [comment]
It's blocked during the `compile` phase.

**Comment by kiwifb** [comment]
It should have been obvious but your command `ebuild sage-doc-9999.ebuild install` sent my brain into a spin.

**Comment by kiwifb** [comment]
Amusing fact, build html+pdf is fine with 6 out of 8 languages in `L10N` but fails with a 7th one.

**Comment by strogdon** [comment]
I have experimented too and removing `ja` sometimes helps. t seems that for some `L10N` extra fonts need to be generated. Also, I have 8 cores and I usually use `MAKEOPTS=-j9`. Sometimes reducing `MAKEOPTS` to `j8` helps.

**Comment by kiwifb** [comment]
I had a successful build by going from `-j8` to `-j6`. We are definitely in the makefile race condition territory - and fixing parallel make actually landed us there :(

**Comment by strogdon** [comment]
The sandbox issue is separate from potential race condition. The sandbox was because 
`fc-cache` was not being run on `/usr/share/texmf-dist/fonts/opentype` and `/usr/share/texmf-dist/fonts/truetype` after installing `dev-texlive/texlive-langjapanese`. Running `fc-cache` generates `.uuid` files. I'm not sure where the fault is but I have one system where the `.uuid` exit and another where they don't.

**Comment by kiwifb** [comment]
Hum
```
fbissey@tarazed ~ $ equery f texlive-langjapanese | grep uuid
fbissey@tarazed ~ $ 
```
but trying to do a `locate .uuid` turned up a file called `/var/db/repos/gentoo/media-libs/fontconfig/files/fontconfig-2.13.1-revert_delete_.uuid_for_empty_directory.patch` which lead me to https://bugs.gentoo.org/666418 which seems relevant.

**Comment by strogdon** [comment]
Relative to parallel make, do you get any mileage out of 
```#!diff
--- src/doc/Makefile.orig       2022-01-26 21:17:03.902985173 -0700
+++ src/doc/Makefile    2022-01-26 21:17:28.791984198 -0700
@@ -56,7 +56,7 @@
        MAKE=$(MAKE) $(PYTHON) -m sage_docbuild $(subst -,/,$(subst doc-pdf--,,$@)) pdf $(SAGE_DOCBUILD_OPTS)
 
 # reference manual, pdf
-doc-pdf-reference: doc-inventory-reference
+doc-pdf-reference: doc-html-reference
        $(eval DOCS = $(shell $(PYTHON) -m sage_docbuild --all-documents reference))
        @if [ -z "$(DOCS)" ]; then echo "Error: '$(PYTHON) -m sage_docbuild --all-documents' failed"; exit 1; fi
        $(eval BIBLIO = $(firstword $(DOCS)))
}}},

This probably increases build time but it seems to help here in situations where the pdf docs failed to build.

**Comment by kiwifb** [comment]
That feels weird, but if there is some inclusion of html element when you build pdf docs it may actually be justified. I will test this later.

**Comment by strogdon** [comment]
On vanilla after `make doc-clean doc-uninstall` and then `make doc-pdf` no latex or pdf stuff is created until after all html stuff is built. And the build is usually pretty fast. So the vanilla build is not strictly in parallel. I `watched` the important folders as the build took place to determine what was built when.

**Comment by strogdon** [comment]
Here, instead of `make doc-html doc-pdf` doing just `make doc-pdf` builds `html` and `pdf` docs?
```
real    18m36.335s
user    110m34.944s
sys     9m57.758s
```
Am I missing something?

**Comment by kiwifb** [comment]
If you mean with your patch above (which I should still test) it would be normal to have the reference manual in html and pdf. Not sure about the other languages guides, which is the weak point of the patch.

**Comment by kiwifb** [comment]
After saying that there is https://github.com/sagemath/sage/blob/develop/src/doc/Makefile#L74 for which I really wonder if there is actually an error.

**Comment by strogdon** [comment]
No patch. Just `sage-doc-9999` but doing only `make doc-pdf` (I had to modify the ebuild). This is what I've had to do on vanilla that builds everything. All the langs build here.

**Comment by kiwifb** [comment]
That's an interesting simplification. But I cannot see it be the product of the Makefile alone, apart from the line I quote above, there is no calls from pdf targets to make html targets. Which means the html is produced by the sage docbuilder when the pdf is.

**Comment by strogdon** [comment]
On vanilla after `make doc-clean doc-uninstall` and then `make doc-pdf` `html + pdf` docs build. Perhaps this is not intended.

**Comment by kiwifb** [comment]
I'd say that's a question for sage-devel.

**Comment by strogdon** [comment]
Perhaps you are correct about the docbuilder. In building things the `en` stuff is always first. I don't see where that is done. And then the order of the other `langs` is not clear.

**Comment by kiwifb** [comment]
The reference stuff which is `en` is always first. I am not sure that for the other guides `en` is always first.

**Comment by strogdon** [comment]
This works here
```#!diff
--- a/sci-mathematics/sage-doc/sage-doc-9999.ebuild
+++ b/sci-mathematics/sage-doc/sage-doc-9999.ebuild
@@ -93,11 +93,11 @@ src_compile(){
        # Needs to be created beforehand or it gets created as a file with the content of _static/plot_directive.css
        mkdir -p "${SAGE_DOC}"/html/en/reference/_static
 
-       target="doc-html "
-
        if use doc-pdf ; then
                DOCS="${SAGE_DOC}/pdf"
-               target="${target}doc-pdf"
+               target="doc-pdf"
+       else
+               target="doc-html"
        fi
 
        # Do not double quote target. We need spaces to be considered spaces and not part of a target name.
```
If USE=-doc-pdf, I get html docs and with USE=doc-pdf I get html+pdf docs. As you mentioned one would think that the Makefile would control this but apparently no. And no race problem. Perhaps the race problem was, previously, because the html docs were being built twice?

**Comment by kiwifb** [comment]
I almost inserted something like that last night. I probably should in the next revisions. Still have to produce some binary docs.

**Comment by kiwifb** [comment]
Closing this now.
