### ISSUE TITLE
pervasive vanilla doctest failures

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#677]
Are these failures Gentoo-related or vanilla-related (numerous instances)
```
Expected nothing
Got:
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libm.so when searching for -lm
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libm.a when searching for -lm
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libpthread.so when searching for -lpthread
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libpthread.a when searching for -lpthread
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libc.so when searching for -lc
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libc.a when searching for -lc
```

**Comment by strogdon** [comment]
OK, this on vanilla
```
sage -t --random-seed=69413530074349955370567111465904931355 src/sage/misc/sagedoc.py
**********************************************************************
File "src/sage/misc/sagedoc.py", line 653, in sage.misc.sagedoc.format
Failed example:
    cython('\n'.join(cython_code))
Expected nothing
Got:
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libm.so when searching for -lm
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libm.a when searching for -lm
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libpthread.so when searching for -lpthread
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libpthread.a when searching for -lpthread
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libc.so when searching for -lc
    /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible ///usr/lib/libc.a when searching for -lc
**********************************************************************
1 item had failures:
   1 of  18 in sage.misc.sagedoc.format
    [104 tests, 1 failure, 18.91 s]
```
fails on Gentoo with
```
sage -t --random-seed=46551679023293788221019914368464485992 /usr/lib/python3.10/site-packages/sage/misc/sagedoc.py
**********************************************************************
File "/usr/lib/python3.10/site-packages/sage/misc/sagedoc.py", line 1545, in sage.misc.sagedoc._sage_doc._open
Failed example:
    browse_sage_doc._open("tutorial", testing=True)[1]  # optional - sagemath_doc_html
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/sage/doctest/forker.py", line 694, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/usr/lib/python3.10/site-packages/sage/doctest/forker.py", line 1088, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.misc.sagedoc._sage_doc._open[1]>", line 1, in <module>
        browse_sage_doc._open("tutorial", testing=True)[Integer(1)]  # optional - sagemath_doc_html
      File "/usr/lib/python3.10/site-packages/sage/misc/sagedoc.py", line 1551, in _open
        raise OSError("""The document '{0}' does not exist.  Please build it
    OSError: The document 'tutorial' does not exist.  Please build it
    with 'sage -docbuild tutorial html' and try again.
**********************************************************************
1 item had failures:
   1 of   3 in sage.misc.sagedoc._sage_doc._open
    [104 tests, 1 failure, 18.67 s]
```
Different reasons.

**Comment by kiwifb** [comment]
Most of the incompatible library message comes from vanilla setting `NTL_LIBDIR` to `/usr/lib` instead of `/usr/lib64`. sage-on-gentoo shouldn't suffer from this.

Second message, not the same doctest failing. I am not sure why it is failing. It should work unless there is an issue with the install of the documentation.

**Comment by kiwifb** [comment]
`NTL_LIBDIR` is set in `sage_conf.py` in vanilla. https://github.com/sagemath/sage/blob/develop/pkgs/sage-conf/sage_conf.py.in#L23

**Comment by strogdon** [comment]
See https://trac.sagemath.org/ticket/33311. The issue is similar to https://trac.sagemath.org/ticket/31578.

**Comment by strogdon** [comment]
Vanilla sage issue resolved. Please give https://trac.sagemath.org/ticket/33311 a positive review. Now to the Gentoo failure, `sage-doc-9999` here ONLY installs `html/en` and that lang is incomplete

```
$ ls /usr/share/doc/sage-doc-9999/html/en/
genindex-all.html  index.html   pdf        search.html     _sources  website
genindex.html      objects.inv  reference  searchindex.js  _static
```
The `pdf` install appears correct
```
$ ls /usr/share/doc/sage-doc-9999/pdf
ca  de  en  es  fr  hu  it  ja  pt  ru  tr
```

**Comment by kiwifb** [comment]
Funny that, I don't have my french stuff either in html but I do in pdf. I am fairly sure that's down to using `emake doc-pdf` instead of `emake doc-html doc-pdf`. Interestingly enough, the doctest pass for me. Then again I currently have a customised `sage-runtests` from https://trac.sagemath.org/ticket/33141 that may interfere.

**Comment by kiwifb** [comment]
Yes, doing `emake doc-pdf` instead of `emake doc-html doc-pdf` was responsible for those missing folders.

**Comment by strogdon** [comment]
So something must have changed.

**Comment by strogdon** [comment]
`emake doc-html doc-pdf` fixed this here also. The vanilla topic is not really an issue. I'll close this - I do have another topic I'll open on doctesting.
