### ISSUE TITLE
sage-doc-9999 with matplotlib-3.4.3-r1 will not build

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#686]
Noticed this on Prefix where I had `matplotlib-3.5.1` masked.
```
[dynamics ] /storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/dynamics/cellular_automata/elementary.py:docstring of sage.dynamics.cellular_automata.elementary.ElementaryCellularAutomata:201: WARNING: Exception occurred in plotting                         elementary-1
[dynamics ]  from /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc/en/reference/dynamics/sage/dynamics/cellular_automata/elementary.rst:
[dynamics ] Traceback (most recent call last):
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/matplotlib/sphinxext/plot_directive.py", line 484, in run_code
[dynamics ]     exec(code, ns)
[dynamics ]   File "<string>", line 4, in <module>
[dynamics ]   File "<string>", line 32, in sphinx_plot
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/graphics.py", line 2766, in matplotlib
[dynamics ]     g._render_on_subplot(subplot)
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/matrix_plot.py", line 175, in _render_on_subplot
[dynamics ]     cmap = get_cmap(options.pop('cmap',None))
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/colors.py", line 1379, in get_cmap
[dynamics ]     from matplotlib import colormaps
[dynamics ] ImportError: cannot import name 'colormaps' from 'matplotlib' (/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/matplotlib/__init__.py)
[dynamics ] /storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/dynamics/cellular_automata/elementary.py:docstring of sage.dynamics.cellular_automata.elementary.ElementaryCellularAutomata:215: WARNING: Exception occurred in plotting                         elementary-2
[dynamics ]  from /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999/src/doc/en/reference/dynamics/sage/dynamics/cellular_automata/elementary.rst:
[dynamics ] Traceback (most recent call last):
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/matplotlib/sphinxext/plot_directive.py", line 484, in run_code
[dynamics ]     exec(code, ns)
[dynamics ]   File "<string>", line 4, in <module>
[dynamics ]   File "<string>", line 32, in sphinx_plot
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/graphics.py", line 2766, in matplotlib
[dynamics ]     g._render_on_subplot(subplot)
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/matrix_plot.py", line 175, in _render_on_subplot
[dynamics ]     cmap = get_cmap(options.pop('cmap',None))
[dynamics ]   File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/plot/colors.py", line 1379, in get_cmap
[dynamics ]     from matplotlib import colormaps
[dynamics ] ImportError: cannot import name 'colormaps' from 'matplotlib' (/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/matplotlib/__init__.py)
/storage/strogdon/gentoo-rap/usr/bin/python3.10 -m sage_docbuild --no-pdf-links reference/graphs inventory --no-prune-empty-dirs
[arithgrou] /storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/matplotlib/__init__.py:152: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
[arithgrou]   if LooseVersion(module.__version__) < minver:
[arithgrou] /storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/setuptools/_distutils/version.py:351: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
[arithgrou]   other = LooseVersion(other)
[arithgrou] building [inventory]: targets for 12 source files that are out of date
[arithgrou] updating environment: [new config] 12 added, 0 changed, 0 removed
[dynamics ] The inventory files are in ../../../build_doc/inventory/en/reference/dynamics.
Error building the documentation.
Traceback (most recent call last):
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/__main__.py", line 2, in <module>
    main()
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 1745, in main
    builder()
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 785, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/__init__.py", line 135, in f
    runsphinx()
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/sphinxbuild.py", line 326, in runsphinx
    sys.stderr.raise_errors()
  File "/storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage_docbuild/sphinxbuild.py", line 262, in raise_errors
    raise OSError(self._error)
OSError: /storage/strogdon/gentoo-rap/usr/lib/python3.10/site-packages/sage/dynamics/cellular_automata/elementary.py:docstring of sage.dynamics.cellular_automata.elementary.ElementaryCellularAutomata:201: WARNING: Exception occurred in plotting elementary-1

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
make[1]: *** [Makefile:20: doc-inventory--reference-dynamics] Error 1
```

**Comment by strogdon** [comment]
Apparently, 3.5.1 was unstable at one time so I masked it to be in sync with Gentoo. Yes, 3.4.3-r1 was installed. I do know that 3.5.1 does work on the Prefix.
