### ISSUE TITLE
dev-python/kiwisolver-1.4.2 fails to emerge

### ISSUE THREAD

**Issue by derekperrin** [cschwan/sage-on-gentoo#689]
I'm trying to emerge sage using the sagemath set, but things seem to be failing when it tries to emerge kiwisolver.

```
>>> Emerging (2 of 42) dev-python/kiwisolver-1.4.2::gentoo
 * kiwi-1.4.2.tar.gz BLAKE2B SHA512 size ;-) ...                                          [ ok ]
>>> Unpacking source...
>>> Unpacking kiwi-1.4.2.tar.gz to /var/tmp/portage/dev-python/kiwisolver-1.4.2/work
>>> Source unpacked in /var/tmp/portage/dev-python/kiwisolver-1.4.2/work
>>> Preparing source in /var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2 ...
 * python3_9: running distutils-r1_run_phase distutils-r1_python_compile
python3.9 setup.py build -j 4
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2/setup.py", line 13, in <module>
    from cppy import CppyBuildExt
ModuleNotFoundError: No module named 'cppy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2/setup.py", line 15, in <module>
    raise RuntimeError(
RuntimeError: Missing setup required dependencies: cppy. Installing through pip as recommended ensure one never hits this issue.
 * ERROR: dev-python/kiwisolver-1.4.2::gentoo failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_compile
 *   environment, line 3053:  Called distutils-r1_src_compile
 *   environment, line 1384:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  573:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2746:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2335:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2333:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line  897:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1372:  Called distutils-r1_python_compile
 *   environment, line 1183:  Called esetup.py 'build' '-j' '4'
 *   environment, line 1874:  Called die
 * The specific snippet of code:
 *       "${@}" || die -n;
 * 
 * If you need support, post the output of `emerge --info '=dev-python/kiwisolver-1.4.2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/kiwisolver-1.4.2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/kiwisolver-1.4.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/kiwisolver-1.4.2/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2'
 * S: '/var/tmp/portage/dev-python/kiwisolver-1.4.2/work/kiwi-1.4.2'
```

**Comment by kiwifb** [comment]
This is most strange, `cppy` is a build dependency of `kiwisolver` and should have been installed before hand. https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-python/kiwisolver/kiwisolver-1.4.2.ebuild 

It appears the addition to `BDEPEND` is quite recent and may not have propagated to your mirror yet https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=7ef4c4cee2d11497160f7c639544b7fafa71a8ca . Just doing `emerge cppy` will fix your problem.

In any case, this is a bug with the main tree not sage-on-gentoo itself.
