### ISSUE TITLE
building sage-doc (html docs)

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#763]
The first item is probably cosmetic but I'm curious as to the origin.

- The terminal output is now very disorderly. This has been present for several betas now where certain output lines seem to be preceded by multiple tabs.

- I'm now seeing multiple `KeyError`s when building the docs. These errors prevent Sage from  starting

```
$ sage
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/sage-config", line 8, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/_sage_conf/__main__.py", line 15, in _main
    stdout.write('{}\n'.format(d[args.VARIABLE]))
                               ~^^^^^^^^^^^^^^^
KeyError: 'SAGE_ROOT'
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.11/sage-config", line 8, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/usr/lib/python3.11/site-packages/_sage_conf/__main__.py", line 15, in _main
    stdout.write('{}\n'.format(d[args.VARIABLE]))
                               ~^^^^^^^^^^^^^^^
KeyError: 'SAGE_LOCAL'
```

**Comment by strogdon** [comment]
With the `KeyError`s sage will start with the above.

**Comment by kiwifb** [comment]
The sage-doc build thing started with either the latest furo or sphinx 7.1. I do not  remember which one. I enabled them almost at the same time.

The keyerror stuff is new and I have not noticed it. Will inspect ASAP.

**Comment by strogdon** [comment]
I thought `sphinx` was maybe the reason but I hadn't noticed the `furo` upgrade. I'm now using `furo-2023.9.10`.

**Comment by kiwifb** [comment]
The previous version of furo was causing trouble and would not work with sphinx 7.1.

**Comment by kiwifb** [comment]
OK, a "good" action never goes unpunished. As a simplification of the stuff I do to sage-conf, I have let it install the `sage-config` executable. It is executed by the sage start up script when found and it is the cause of the complaints. I will make it disappear again.

**Comment by kiwifb** [comment]
keyerror fixed by 36e29168bc6202873670571cd39dde260e97d013, sync and rebuild sage-conf. The offending messages should go away.
