### ISSUE TITLE
sci-mathematics/sage-doc-10.4 fails to build

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#791]
emerge -pv sci-mathematics/sage-doc

[ebuild     U ~] sci-mathematics/sage-doc-10.4::sage-on-gentoo [10.3::sage-on-gentoo] USE="-doc-pdf" L10N="-ca -de -es fr -hu -it -ja -pt -ru -tr" 0 KiB

egrf sci-mathematics/sage-doc

 * dependency graph for sci-mathematics/sage-doc-10.4
 `--  sci-mathematics/sage-doc-10.4  ~amd64 
   `--  dev-libs/mathjax-3.2.2-r2  (dev-libs/mathjax) amd64 
   `--  dev-lang/python-3.12.3-r1  (dev-lang/python) amd64  [readline sqlite]
   `--  dev-python/sphinx-7.3.7-r2  (dev-python/sphinx) amd64  [python_targets_python3_12(-)]
   `--  dev-python/furo-2024.5.6  (dev-python/furo) amd64  [python_targets_python3_12(-)]
   `--  dev-python/jupyter-sphinx-0.5.3  (dev-python/jupyter-sphinx) ~amd64  [python_targets_python3_12(-)]
   `--  dev-python/sphinx-copybutton-0.5.2  (dev-python/sphinx-copybutton) ~amd64  [python_targets_python3_12(-)]
   `--  dev-python/sphinx-inline-tabs-2023.4.21  (dev-python/sphinx-inline-tabs) ~amd64  [python_targets_python3_12(-)]
   `--  sci-mathematics/sagemath-standard-10.4  (~sci-mathematics/sagemath-standard-10.4) ~amd64  [python_targets_python3_12(-) jmol]
   `--  sci-mathematics/sage_docbuild-10.4  (~sci-mathematics/sage_docbuild-10.4) ~amd64  [python_targets_python3_12(-)]
   `--  dev-lang/python-3.11.9-r1  (dev-lang/python) ~amd64  [readline sqlite]
   `--  dev-lang/python-3.10.14_p1-r1  (dev-lang/python) ~amd64  [readline sqlite]
   `--  app-text/texlive-2023  (>=app-text/texlive-2023) amd64  [extra luatex l10n_en l10n_ca? l10n_de? l10n_es? l10n_fr? l10n_hu? l10n_it? l10n_ja? l10n_pt? l10n_ru? l10n_tr?]
   `--  app-text/texlive-core-2023-r9  (>=app-text/texlive-core-2023) amd64  [xindy]
   `--  media-fonts/freefont-20120503  (media-fonts/freefont) amd64 
[ sci-mathematics/sage-doc-10.4 stats: packages (15), max depth (1) ]

[sci-mathematics:sage-doc-10.4:20240721-185646.log.gz](https://github.com/user-attachments/files/16325836/sci-mathematics.sage-doc-10.4.20240721-185646.log.gz)

**Comment by CaptainBloodz** [comment]
Log snippet:
sage --docbuild --no-pdf-links reference/plotting inventory --no-prune-empty-dirs
[plotting ] building [inventory]: targets for 32 source files that are out of date
[plotting ] updating environment: [new config] 32 added, 0 changed, 0 removed
lcalc: invalid option -- 'e'
[plotting ] /usr/lib/python3.11/site-packages/sphinx/util/inspect.py:374: DeprecationWarning:
[plotting ] Importing line2d from here is deprecated; please use "from sage.plot.line import line2d" instead.
[plotting ] See https://github.com/sagemath/sage/issues/28717 for details.
[plotting ]   return getattr(obj, name, *defargs)
[plotting ] docstring of sage.plot.complex_plot.complex_plot:160: WARNING: Exception occurred in plotting complex_plot-8
[plotting ]  from /var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc/en/reference/plotting/sage/plot/complex_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 2, in <module>
[plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__ (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/misc/lazy_import.c:6291)
[plotting ]     return self.get_object()(*args, **kwds)
[plotting ]   File "/usr/lib/python3.11/site-packages/sage/misc/decorators.py", line 497, in wrapper
[plotting ]     return func(*args, **options)
[plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:14985)
[plotting ]     rgbs = complex_to_cmap_rgb(
[plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:11857)
[plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:12472)
[plotting ]     hls = rgb_to_hls(rgb)
[plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:15662)
[plotting ]     delta = rgb.ptp(-1)
[plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
[plotting ] docstring of sage.plot.complex_plot.complex_plot:174: WARNING: Exception occurred in plotting complex_plot-9
[plotting ]  from /var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc/en/reference/plotting/sage/plot/complex_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 2, in <module>
[plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__ (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/misc/lazy_import.c:6291)
[plotting ]     return self.get_object()(*args, **kwds)
[plotting ]   File "/usr/lib/python3.11/site-packages/sage/misc/decorators.py", line 497, in wrapper
[plotting ]     return func(*args, **options)
[plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:14985)
[plotting ]     rgbs = complex_to_cmap_rgb(
[plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:11857)
[plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:12472)
[plotting ]     hls = rgb_to_hls(rgb)
[plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:15662)
[plotting ]     delta = rgb.ptp(-1)
[plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
[plotting ] docstring of sage.plot.complex_plot.complex_plot:226: WARNING: Exception occurred in plotting complex_plot-13
[plotting ]  from /var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc/en/reference/plotting/sage/plot/complex_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 2, in <module>
[plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__ (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/misc/lazy_import.c:6291)
[plotting ]     return self.get_object()(*args, **kwds)
[plotting ]   File "/usr/lib/python3.11/site-packages/sage/misc/decorators.py", line 497, in wrapper
[plotting ]     return func(*args, **options)
[plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:14985)
[plotting ]     rgbs = complex_to_cmap_rgb(
[plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:11857)
[plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:12472)
[plotting ]     hls = rgb_to_hls(rgb)
[plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:15662)
[plotting ]     delta = rgb.ptp(-1)
[plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
[plotting ] docstring of sage.plot.complex_plot.complex_plot:267: WARNING: Exception occurred in plotting complex_plot-17
[plotting ]  from /var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc/en/reference/plotting/sage/plot/complex_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 1, in <module>
[plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__ (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/misc/lazy_import.c:6291)
[plotting ]     return self.get_object()(*args, **kwds)
[plotting ]   File "/usr/lib/python3.11/site-packages/sage/misc/decorators.py", line 497, in wrapper
[plotting ]     return func(*args, **options)
[plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:14985)
[plotting ]     rgbs = complex_to_cmap_rgb(
[plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:11857)
[plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:12472)
[plotting ]     hls = rgb_to_hls(rgb)
[plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:15662)
[plotting ]     delta = rgb.ptp(-1)
[plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
[plotting ] docstring of sage.plot.complex_plot.complex_plot:277: WARNING: Exception occurred in plotting complex_plot-18
[plotting ]  from /var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc/en/reference/plotting/sage/plot/complex_plot.rst:
[plotting ] Traceback (most recent call last):
[plotting ]   File "/usr/lib/python3.11/site-packages/matplotlib/sphinxext/plot_directive.py", line 552, in _run_code
[plotting ]     exec(code, ns)
[plotting ]   File "<string>", line 1, in <module>
[plotting ]   File "sage/misc/lazy_import.pyx", line 410, in sage.misc.lazy_import.LazyImport.__call__ (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/misc/lazy_import.c:6291)
[plotting ]     return self.get_object()(*args, **kwds)
[plotting ]   File "/usr/lib/python3.11/site-packages/sage/misc/decorators.py", line 497, in wrapper
[plotting ]     return func(*args, **options)
[plotting ]            ^^^^^^^^^^^^^^^^^^^^^^
[plotting ]   File "sage/plot/complex_plot.pyx", line 1221, in sage.plot.complex_plot.complex_plot (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:14985)
[plotting ]     rgbs = complex_to_cmap_rgb(
[plotting ]   File "sage/plot/complex_plot.pyx", line 623, in sage.plot.complex_plot.complex_to_cmap_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:11857)
[plotting ]     rgbs = add_contours_to_rgb(normalized_colors, lightdeltas, dark_rate=dark_rate)
[plotting ]   File "sage/plot/complex_plot.pyx", line 760, in sage.plot.complex_plot.add_contours_to_rgb (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:12472)
[plotting ]     hls = rgb_to_hls(rgb)
[plotting ]   File "sage/plot/complex_plot.pyx", line 1293, in sage.plot.complex_plot.rgb_to_hls (/var/no-tmpfs/portage/sci-mathematics/sagemath-standard-10.4/work/sagemath_standard-10.4-python3_11/build/cythonized/sage/plot/complex_plot.c:15662)
[plotting ]     delta = rgb.ptp(-1)
[plotting ] AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.
[plotting ] The inventory file is in ../../../build_doc/inventory/en/reference/plotting.
Error building the documentation.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/sage_docbuild/__main__.py", line 530, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/sage_docbuild/__main__.py", line 526, in main
    builder()
  File "/usr/lib/python3.11/site-packages/sage_docbuild/builders.py", line 827, in _wrapper
    getattr(DocBuilder, build_type)(self, *args, **kwds)
  File "/usr/lib/python3.11/site-packages/sage_docbuild/builders.py", line 163, in f
    runsphinx()
  File "/usr/lib/python3.11/site-packages/sage_docbuild/sphinxbuild.py", line 319, in runsphinx
    sys.stderr.raise_errors()
  File "/usr/lib/python3.11/site-packages/sage_docbuild/sphinxbuild.py", line 255, in raise_errors
    raise OSError(self._error)
OSError: docstring of sage.plot.complex_plot.complex_plot:160: WARNING: Exception occurred in plotting complex_plot-8

    Note: incremental documentation builds sometimes cause spurious
    error messages. To be certain that these are real errors, run
    "make doc-clean doc-uninstall" first and try again.
make[1]: *** [Makefile:28: doc-inventory--reference-plotting] Error 1
make[1]: Leaving directory '/var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc'
make: *** [Makefile:41: doc-inventory-reference] Error 2
 * ERROR: sci-mathematics/sage-doc-10.4::sage-on-gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/sage-doc-10.4::sage-on-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/sage-doc-10.4::sage-on-gentoo'`.
 * The complete build log is located at '/var/log/portage/sci-mathematics:sage-doc-10.4:20240721-185646.log.gz'.
 * For convenience, a symlink to the build log is located at '/var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/temp/build.log.gz'.
 * The ebuild environment file is located at '/var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/temp/environment'.
 * Working directory: '/var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4/src/doc'
 * S: '/var/no-tmpfs/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4'

>>> Failed to emerge sci-mathematics/sage-doc-10.4, Log file:

**Comment by CaptainBloodz** [comment]
Duplicate
