### ISSUE TITLE
cython 3.0.11 breaks building sagemath-standard

### ISSUE THREAD

**Issue by kiwifb** [cschwan/sage-on-gentoo#794]
As the title says. The final error is reminiscent of #783 but in the end quite different in its causes.
```
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 443, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 439, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 229, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 221, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 415, in build_wheel
    return self._build_with_temp_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
    exec(code, locals())
  File "<string>", line 95, in <module>
  File "/usr/lib/python3.12/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
    self.run_command("build")
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/sage_setup/command/sage_build_ext.py", line 25, in run
    self.run_command('build_cython')
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/usr/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.12/site-packages/sage_setup/command/sage_build_cython.py", line 220, in run
    extensions = cythonize(
                 ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1150, in cythonize
    result.get(99999)  # seconds
    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
Cython.Compiler.Errors.CompileError: sage/matroids/circuit_closures_matroid.pyx
```
but in fact this starts much earlier during cythonizing
```

Error compiling Cython file:
------------------------------------------------------------
...
        """
        self._pack(self._input, F)
        self.__max_independent(self._output, self._input)
        return self.__unpack(self._output)

    cpdef int _rank(self, frozenset F):
          ^
------------------------------------------------------------

sage/matroids/basis_exchange_matroid.pyx:655:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int _stored_full_rank
    cdef int _stored_size

    # virtual methods
    cpdef frozenset groundset(self)
    cpdef int _rank(self, frozenset X)
                   ^
------------------------------------------------------------

sage/matroids/matroid.pxd:12:19: Previous declaration is here
warning: sage/matroids/basis_exchange_matroid.pyx:799:21: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

Error compiling Cython file:
------------------------------------------------------------
...
        """
        self._pack(self._input, F)
        self.__max_coindependent(self._output, self._input)
        return self.__unpack(self._output)

    cpdef int _corank(self, frozenset F):
          ^
------------------------------------------------------------

sage/matroids/basis_exchange_matroid.pyx:799:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    # internal methods, assuming verified input
    cpdef frozenset _max_independent(self, frozenset X)
    cpdef frozenset _circuit(self, frozenset X)
    cpdef frozenset _fundamental_circuit(self, frozenset B, e)
    cpdef frozenset _closure(self, frozenset X)
    cpdef int _corank(self, frozenset X)
                     ^
------------------------------------------------------------

sage/matroids/matroid.pxd:19:21: Previous declaration is here
warning: sage/matroids/basis_exchange_matroid.pyx:943:30: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

Error compiling Cython file:
------------------------------------------------------------
...
        self._pack(self._input, X)
        self._pack(self._input2, Y)
        self.__augment(self._output, self._input, self._input2)
        return self.__unpack(self._output)

    cpdef bint _is_independent(self, frozenset F):
          ^
------------------------------------------------------------

sage/matroids/basis_exchange_matroid.pyx:943:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef frozenset _cocircuit(self, frozenset X)
    cpdef frozenset _fundamental_cocircuit(self, frozenset B, e)
    cpdef frozenset _coclosure(self, frozenset X)
    cpdef frozenset _augment(self, frozenset X, frozenset Y)

    cpdef bint _is_independent(self, frozenset X)
                              ^
------------------------------------------------------------

sage/matroids/matroid.pxd:26:30: Previous declaration is here
warning: sage/matroids/basis_exchange_matroid.pyx:2234:23: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

Error compiling Cython file:
------------------------------------------------------------
...
            if self.__is_isomorphism(other, morphism):
                return True

        return self._characteristic_setsystem()._isomorphism(other._characteristic_setsystem(), PS, PO) is not None

    cpdef bint is_valid(self):
          ^
------------------------------------------------------------

sage/matroids/basis_exchange_matroid.pyx:2234:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef is_cobasis(self, X)
    cpdef is_cocircuit(self, X)
    cpdef is_coclosed(self, X)

    # verification
    cpdef bint is_valid(self)
                       ^
------------------------------------------------------------

sage/matroids/matroid.pxd:108:23: Previous declaration is here
warning: sage/matroids/circuit_closures_matroid.pyx:182:19: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

Error compiling Cython file:
------------------------------------------------------------
...
            sage: sorted(M.groundset())
            ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']
        """
        return frozenset(self._groundset)

    cpdef int _rank(self, frozenset X):
          ^
------------------------------------------------------------

sage/matroids/circuit_closures_matroid.pyx:182:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cdef int _stored_full_rank
    cdef int _stored_size

    # virtual methods
    cpdef frozenset groundset(self)
    cpdef int _rank(self, frozenset X)
                   ^
------------------------------------------------------------

sage/matroids/matroid.pxd:12:19: Previous declaration is here
warning: sage/matroids/circuit_closures_matroid.pyx:224:30: Implicit noexcept declaration is deprecated. Function declaration should contain 'noexcept' keyword.

Error compiling Cython file:
------------------------------------------------------------
...
            sage: M.dual().full_rank()
            4
        """
        return self._matroid_rank

    cpdef bint _is_independent(self, frozenset F):
          ^
------------------------------------------------------------

sage/matroids/circuit_closures_matroid.pyx:224:10: Signature not compatible with previous declaration

Error compiling Cython file:
------------------------------------------------------------
...
    cpdef frozenset _cocircuit(self, frozenset X)
    cpdef frozenset _fundamental_cocircuit(self, frozenset B, e)
    cpdef frozenset _coclosure(self, frozenset X)
    cpdef frozenset _augment(self, frozenset X, frozenset Y)

    cpdef bint _is_independent(self, frozenset X)
                              ^
------------------------------------------------------------

sage/matroids/matroid.pxd:26:30: Previous declaration is here
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1350, in cythonize_one_helper
    return cythonize_one(*m)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1326, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: sage/matroids/circuit_closures_matroid.pyx
```
this works perfectly with cython 3.0.10.

**Comment by kiwifb** [comment]
Similar cython errors show up in `sage/matroids/flats_matroid.pyx`, `sage/matroids/matroid.pyx`, `sage/matroids/union_matroid.pyx`, `sage/matroids/graphic_matroid.pyx`, `sage/matroids/linear_matroid.pyx` and `sage/sets/disjoint_set.pyx`

**Comment by kiwifb** [comment]
And `sage/matroids/basis_exchange_matroid.pyx`. I cannot exclude missing a few others.

**Comment by strogdon** [comment]
sage with `cython-3.0.11` and the regression patch https://github.com/void-linux/void-packages/commit/b5926bd0342911d1547f37a862082ab73ee1644e does build. However, the regression patch does not appear under https://github.com/cython/cython/commits/master/

**Comment by kiwifb** [comment]
I have a patch in the vbraun branch and we are working on something a bit better upstream. sage needs to get rid of those things anyway. Fun fact, cypari2 from the main tree is also failing to build with cython 3.0.11 from the tree - 2.2.0 which I am pushing, does not have the problem.

**Comment by kiwifb** [comment]
OK, my work on getting cython 3.0.11 to work with sage is merged and officially out in the current dev branch. I am experimenting with a new way to distribute patches from upstream PR so once I merge my current development branch sage 10.4 will have support for cython 3.0.11 (you may have to update cypari2 to 2.0.0 as well). The way I distribute the patch is experimental, report issues please
The merge will be done in the next hour.

**Comment by strogdon** [comment]
After a length system update I see:
```
 * Applying sagemath-standard-10.4b-neutering.patch ...
 [ ok ]
 * Build system packages:
 *   dev-python/gpep517            : 16
 *   dev-python/installer          : 0.7.0
 *   dev-python/cython             : 3.0.11
 *   dev-python/setuptools         : 72.2.0
 *   dev-python/setuptools-rust    : 1.10.1
 *   dev-python/setuptools-scm     : 8.1.0
 *   dev-python/wheel              : 0.44.0
/var/tmp/portage/sci-mathematics/sagemath-standard-9999/temp/environment: line 4998: /var/tmp/portage/sci-mathematics/sagemath-standard-9999/distdir/38113_proc.patch: Permission denied
 * ERROR: sci-mathematics/sagemath-standard-9999::sage-on-gentoo failed (prepare phase):
 *   patch for PR 38113 not found
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_prepare
 *   environment, line 5046:  Called distutils-r1_src_prepare
 *   environment, line 2211:  Called python_prepare_all
 *   environment, line 4815:  Called sage-git-patch_patch
 *   environment, line 4998:  Called die
 * The specific snippet of code:
 *           filterdiff -i '*/${tree}/*' "${DISTDIR}/sagemath_PR${patch}.patch" > "${DISTDIR}/${patch}_proc.patch" || die "patch for PR ${patch} not found";
```
Perhaps the patch file had been misnamed?

```
# ls -al /var/tmp/portage/sci-mathematics/sagemath-standard-9999/distdir/
total 2
drwxr-xr-x 2 root    portage 1024 Sep  4 14:52 .
drwx------ 8 portage portage 1024 Sep  4 14:53 ..
lrwxrwxrwx 1 root    root      43 Sep  4 14:52 sagemath_PR38113.patch -> /var/cache/distfiles/sagemath_PR38113.patch
```

**Comment by kiwifb** [comment]
Looks like I may have done something stupid, but I should have caught it. Let me check all that.

**Comment by kiwifb** [comment]
Yes, I try to process the patch somewhere I should not have. I need to update the eclass.

**Comment by kiwifb** [comment]
OK, I have updated the eclass, it should take about 15mn for the gentoo mirror to update.

**Comment by strogdon** [comment]
`sagemath-standard-9999` now builds but `sage-doc-9999` fails.

**Comment by n1ghtbyte** [comment]
I'm having the same problem emerging it as in
` File "/usr/lib/python3.12/site-packages/sage_setup/command/sage_build_cython.py", line 220, in run
    extensions = cythonize(
                 ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1150, in cythonize
    result.get(99999)  # seconds
    ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
Cython.Compiler.Errors.CompileError: sage/matroids/circuits_matroid.pyx`
Should it not be solved already? (reading from the previous replies it seemed like it was already partially solved)

**Comment by Etn40ff** [comment]
A dirty workaround is to downgrade to cython 3.0.10, install sagemath-standard then update cython again

**Comment by kiwifb** [comment]
> I'm having the same problem emerging it as in ` File "/usr/lib/python3.12/site-packages/sage_setup/command/sage_build_cython.py", line 220, in run extensions = cythonize( ^^^^^^^^^^ File "/usr/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1150, in cythonize result.get(99999) # seconds ^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/multiprocessing/pool.py", line 774, in get raise self._value Cython.Compiler.Errors.CompileError: sage/matroids/circuits_matroid.pyx` Should it not be solved already? (reading from the previous replies it seemed like it was already partially solved)

I am fairly sure that's a different issue. What is your version of `scikit-build-core`?

**Comment by kiwifb** [comment]
Note to self: do not answer things right off the bed. Yes, this should have been fixed. Could you provide logs that cover the src_prepare phase when patches are supposed to be applied?

**Comment by kiwifb** [comment]
Looks like my new patching strategy is faulty for cython 3.0.11. It must fall in the bucket where it cannot be used. Going back to the mega patch.

**Comment by kiwifb** [comment]
Turns out I used the wrong kind of quotes when I last updated my patching eclass to handle different packages more programmatically. It turned all the patches in empty files, no patching with no errors. Fix pushed.

**Comment by strogdon** [comment]
This is curious since I was able to install `sagemath-standard-9999`(10.5.beta4) without issue.

**Comment by strogdon** [comment]
The changes to the `sage-git-patch.eclass` do not affect building of `sagemath-standard-9999`, so perhaps the building issue pertains to `sagemath-standard-10.4-r2` only.

**Comment by kiwifb** [comment]
That's because sagemath-standard-9999 does not have any eclass managed patch right now. Most of the patches managed by this eclass will be backport of stuff merged in dev with the occasional pending PR (which may then be in 9999). All the patches managed by the eclass in 10.4 have now been merged upstream.

**Comment by n1ghtbyte** [comment]
kiwifb, I was able to build sage given the Etn40ff's advice to downgrade cython, I'm having issues building the sage-doc though. I have the version 0.10.6 of scikit-build-core installed. Do you still want the logs for the src_prepare phase?

**Comment by kiwifb** [comment]
No need for the src_prepare logs. I was able to reproduce the issue because it was so general. What is the issue with sage-doc?

**Comment by n1ghtbyte** [comment]
kiwifw, this is the error (I have no idea how to debug this, other than it's probably a patch's fault)
```
 * Package:    sci-mathematics/sage-doc-10.4:0
 * Repository: sage-on-gentoo
 * Maintainer: frp.bissey@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * Checking whether python3_12 is suitable ...
 *   dev-lang/python:3.12[readline,sqlite] ...                                                                  [ ok ]
 *   python_check_deps ...
 *     dev-python/sphinx[python_targets_python3_12(-)] ...                                                      [ ok ]
 *     ~sci-mathematics/sagemath-standard-10.4[python_targets_python3_12(-),jmol] ...                           [ ok ]
 *     ~sci-mathematics/sage_docbuild-10.4[python_targets_python3_12(-)] ...                                    [ ok ]
 *     dev-python/furo[python_targets_python3_12(-)] ...                                                        [ ok ]
 *     dev-python/jupyter-sphinx[python_targets_python3_12(-)] ...                                              [ ok ]
 *     dev-python/sphinx-copybutton[python_targets_python3_12(-)] ...                                           [ ok ]
 *     dev-python/sphinx-inline-tabs[python_targets_python3_12(-)] ...                                          [ ok ]
 * Using python3.12 to build (via PYTHON_COMPAT iteration)
>>> Unpacking source...
>>> Unpacking sage-doc-10.4.tar.gz to /var/tmp/portage/sci-mathematics/sage-doc-10.4/work
>>> Unpacking sagemath_PR38250.patch to /var/tmp/portage/sci-mathematics/sage-doc-10.4/work
>>> Source unpacked in /var/tmp/portage/sci-mathematics/sage-doc-10.4/work
>>> Preparing source in /var/tmp/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4 ...
 * Applying sage-doc-10.4-makefile.patch ...                                                                    [ ok ]
Processing for src/doc
 * Applying 38250_proc.patch ...
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/doc/en/faq/faq-usage.rst b/src/doc/en/faq/faq-usage.rst
|index 53f225fd729..d03881c36a2 100644
|--- a/src/doc/en/faq/faq-usage.rst
|+++ b/src/doc/en/faq/faq-usage.rst
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 18
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst b/src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
|index b5eb3d842a2..958a378f945 100644
|--- a/src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
|+++ b/src/doc/en/prep/Quickstarts/Statistics-and-Distributions.rst
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 31
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/doc/en/thematic_tutorials/numerical_sage/numpy.rst b/src/doc/en/thematic_tutorials/numerical_sage/numpy.rst
|index dbc2de71d42..925e5312882 100644
|--- a/src/doc/en/thematic_tutorials/numerical_sage/numpy.rst
|+++ b/src/doc/en/thematic_tutorials/numerical_sage/numpy.rst
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 44
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/doc/it/faq/faq-usage.rst b/src/doc/it/faq/faq-usage.rst
|index 37bef7b13c1..5d3183769f7 100644
|--- a/src/doc/it/faq/faq-usage.rst
|+++ b/src/doc/it/faq/faq-usage.rst
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored                                                                                         [ !! ]
 * ERROR: sci-mathematics/sage-doc-10.4::sage-on-gentoo failed (prepare phase):
 *   patch -p1 -p2 failed with /var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/38250_proc.patch
 * 
 * Call stack:
 *               ebuild.sh, line  136:  Called src_prepare
 *             environment, line 2223:  Called sage-git-patch_patch
 *             environment, line 2164:  Called eapply '-p2' '/var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/38250_proc.patch'
 *             environment, line  973:  Called _eapply_patch '/var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/38250_proc.patch'
 *             environment, line  911:  Called __helpers_die 'patch -p1 -p2 failed with /var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/38250_proc.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *   		die "$@"
 * 
 * If you need support, post the output of `emerge --info '=sci-mathematics/sage-doc-10.4::sage-on-gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sci-mathematics/sage-doc-10.4::sage-on-gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/sage-doc-10.4/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4'
 * S: '/var/tmp/portage/sci-mathematics/sage-doc-10.4/work/sage-10.4'
 ```

**Comment by kiwifb** [comment]
OK, I officially try to be too smart and it comes back to bite. I think I see what's going on.

**Comment by kiwifb** [comment]
Fix tested and pushed, you can expect the gentoo mirror of the overlay to be updated in about 15mn.

**Comment by n1ghtbyte** [comment]
Working great! Thank you :)

**Comment by kiwifb** [comment]
Closing the issue.
